const test=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');const os=require('node:os');const path=require('node:path');
const {createDatabase}=require('../src/database.cjs');
function tempDb(){const dir=fs.mkdtempSync(path.join(os.tmpdir(),'r3-media-'));return createDatabase(path.join(dir,'media.db'))}
const title={id:'tt123',type:'series',title:'Test Show',poster:'https://poster',genres:['Drama','Mystery'],year:'2026'};
test('tracking persists a title and can remove it',()=>{const db=tempDb();db.track(title);assert.equal(db.isTracked('tt123'),true);assert.equal(db.tracked()[0].title,'Test Show');db.untrack('tt123');assert.equal(db.isTracked('tt123'),false);db.close()});
test('watch history records episodes and aggregates preferred genres',()=>{const db=tempDb();db.markWatched(title,{season:1,episode:2});db.markWatched({...title,id:'tt456',genres:['Drama','Sci-Fi']},{});assert.equal(db.history().length,2);assert.deepEqual(db.preferredGenres(2),['Drama','Mystery']);db.close()});
test('catalog cache expires and returns parsed payload before expiry',()=>{const db=tempDb();db.putCache('movies',[{id:'a'}],60000);assert.deepEqual(db.getCache('movies'),[{id:'a'}]);db.putCache('expired',[1],-1);assert.equal(db.getCache('expired'),null);db.close()});
test('tracked updates identify released episodes after the last watched episode',()=>{const db=tempDb();db.track(title);db.markWatched(title,{season:1,episode:1});const updates=db.trackedUpdates([{...title,videos:[{season:1,episode:1,released:'2026-01-01'},{season:1,episode:2,released:'2026-01-08'}]}],new Date('2026-02-01'));assert.equal(updates[0].newEpisodeCount,1);db.close()});
test('tracking an existing show establishes a baseline so old episodes are not reported as new',()=>{const db=tempDb();const atTrack={...title,videos:[{season:1,episode:1,released:'2026-01-01'},{season:1,episode:2,released:'2026-01-08'}]};db.track(atTrack,new Date('2026-02-01'));assert.equal(db.trackedUpdates([atTrack],new Date('2026-02-01')).length,0);const later={...atTrack,videos:[...atTrack.videos,{season:1,episode:3,released:'2026-02-08'}]};assert.equal(db.trackedUpdates([later],new Date('2026-03-01'))[0].newEpisodeCount,1);db.close()});
