const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const root=path.join(__dirname,'..'),css=fs.readFileSync(path.join(root,'src/styles.css'),'utf8'),renderer=fs.readFileSync(path.join(root,'src/renderer.js'),'utf8');
function lastRule(selector){const matches=[...css.matchAll(new RegExp(selector.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')+'\\{([^}]+)\\}','g'))];return matches.at(-1)?.[1]||''}
test('series details use one modal scrollbar and a readable two-column episode list',()=>{const rule=lastRule('.episode-grid');assert.match(rule,/overflow:visible/);assert.match(rule,/max-height:none/);assert.match(rule,/grid-template-columns:repeat\(2,minmax\(0,1fr\)\)/);assert.doesNotMatch(rule,/overflow:auto|overflow-y:auto/)});
test('series actions appear before the episode list and episode labels include season and episode',()=>{assert.match(renderer,/class="button-row detail-actions"/);assert.ok(renderer.indexOf('class="button-row detail-actions"')<renderer.indexOf('${episodes.length?episodeSelector'));assert.match(renderer,/S\$\{season\} E\$\{episode\}/)});
test('episode badges keep season and episode on one readable line',()=>{const rule=lastRule('.episode-select>span');assert.match(rule,/flex:0 0 76px/);assert.match(rule,/white-space:nowrap/)});
test('each episode tile exposes a dedicated play button and a watched toggle, not just a single select action',()=>{assert.match(renderer,/data-episode-play="\$\{i\}"/);assert.match(renderer,/data-episode-toggle="\$\{i\}"/);assert.match(renderer,/function toggleEpisodeWatched/)});
test('the selected-episode header numeric-coerces the episode field before interpolating it into HTML, since a Cinemeta episode value is not otherwise sanitized',()=>{assert.doesNotMatch(renderer,/id="selectedEpisode">S\$\{activeSeason\} E\$\{episodes\[selected\]\?\.episode\|\|episodes\[selected\]\?\.number\|\|1\}/);assert.match(renderer,/id="selectedEpisode">S\$\{activeSeason\} E\$\{Number\(episodes\[selected\]\?\.episode\?\?episodes\[selected\]\?\.number\)\|\|1\}/)});
test('the season watched button turns green once every episode in the active season is watched, and updates on toggle and season-tab switches',()=>{assert.match(renderer,/function updateSeasonWatchedButton\(meta,episodes\)/);assert.match(renderer,/button\.classList\.toggle\('season-complete',complete\)/);assert.match(renderer,/updateSeasonWatchedButton\(meta,episodes\)\}$/m);assert.match(renderer,/data-season\][\s\S]{0,400}updateSeasonWatchedButton\(meta,episodes\)/);assert.match(css,/#markWatched\.season-complete\{[^}]*background:#42e09b1c/)});
test('the play button offers a dropdown to pick a specific cached stream instead of only the best one, populated on click from the currently selected episode',()=>{assert.match(renderer,/class="play-split"/);assert.match(renderer,/id="playBestCaret"/);assert.match(renderer,/id="streamMenu"/);assert.match(renderer,/async function toggleStreamMenu\(meta,episodes\)/);assert.match(renderer,/window\.mediaHub\.resolve\(meta\.type,id\)/);assert.match(renderer,/const playback=selectedPlayback\(episodes\),id=playback\.id\|\|meta\.id;try\{const result=await window\.mediaHub\.resolve/);assert.match(renderer,/playBestCaret'\)\.onclick=\(\)=>toggleStreamMenu\(meta,episodes\)/);assert.match(css,/\.stream-menu\{[^}]*position:absolute/);assert.match(css,/\.stream-menu\.hidden\{display:none\}/)});
test('the stream menu closes instead of showing a stale list when the episode selection or season tab changes',()=>{assert.match(renderer,/function selectEpisode\(episodes,index\)\{const episode=episodes\[index\];if\(!episode\)return;closeStreamMenu\(\)/);assert.match(renderer,/data-season\]'\)\.forEach\(button=>button\.onclick=\(\)=>\{closeStreamMenu\(\)/)});
