const {app,BrowserWindow,ipcMain}=require('electron');
const path=require('node:path'),fs=require('node:fs');
const {filterCatalog,episodeWatchState}=require('../src/core.cjs');
app.setPath('userData',path.join(__dirname,'..','.capture-profile'));
const delay=ms=>new Promise(resolve=>setTimeout(resolve,ms));
app.whenReady().then(async()=>{
 const demo=(type,i=0)=>({id:`tt-${type}-${i}`,simklId:type==='series'?1000+i:null,title:type==='movie'?`Movie Feature ${i+1}`:type==='series'?`Series Feature ${i+1}`:`Anime Feature ${i+1}`,type,poster:'assets/app-icon.png',background:'assets/brand-wide.png',year:String(2026-i%12),description:'Live catalog artwork, metadata, ratings and genre filters.',rating:String(6.2+(i%30)/10),runtime:'52 min',genres:i%3===0?['Action','Sci-Fi']:i%3===1?['Drama']:['Comedy','Family'],trailers:[{source:'dQw4w9WgXcQ',name:'Official trailer'}]});
 ipcMain.handle('app:bootstrap',()=>({configured:true,user:{email:'Cinema profile'},library:[]}));
 ipcMain.handle('settings:get',()=>({theme:'ocean',simklClientId:'',torboxConnected:true,vlcInstalled:true,themes:[{id:'neon',name:'Neon Noir',description:'Signature magenta command center'},{id:'midnight',name:'Midnight Gold',description:'Deep black with warm gold highlights'},{id:'ocean',name:'Abyssal Ocean',description:'Navy glass with electric cyan'},{id:'ember',name:'Ember Protocol',description:'Carbon black with molten orange'},{id:'terminal',name:'Ghost Terminal',description:'Tactical graphite and phosphor green'}]}));ipcMain.handle('settings:set-theme',(_e,theme)=>({theme}));ipcMain.handle('account:logout',()=>({ok:true}));ipcMain.handle('playback:stop',()=>({ok:true}));
 ipcMain.handle('home:personalized',()=>({tracked:[],updates:[],recommendations:Array.from({length:10},(_,i)=>demo('movie',i)),preferredGenres:['Action']}));
 ipcMain.handle('catalog:list',(_e,{kind:type})=>Array.from({length:type==='anime'?180:720},(_,i)=>demo(type,i)));
 ipcMain.on('catalog:filter',(event,payload)=>{event.returnValue=filterCatalog(payload.items,payload.section,payload.query,payload.options)});ipcMain.on('episodes:progress',(event,payload)=>{const state=episodeWatchState(payload.episodes,payload.history,payload.id);event.returnValue={...state,watchedKeys:[...state.watchedKeys]}});
 ipcMain.handle('catalog:meta',(_e,{type,id})=>({...demo(type,Number(String(id).split('-').at(-1))||0),id,videos:type==='series'?Array.from({length:20},(_,i)=>({id:`${id}:${i<10?1:2}:${i%10+1}`,season:i<10?1:2,episode:i%10+1,title:`The cinematic episode ${i+1}`})):[]}));
 ipcMain.handle('tracking:list',()=>({tracked:[],history:Array.from({length:6},(_,i)=>({id:'tt-series-0',season:1,episode:i+1}))}));
 ipcMain.handle('library:list',()=>[{id:'1',title:'Dune: Part Two',type:'library',mediaType:'movie',year:'2024',poster:'assets/app-icon.png',background:'assets/brand-wide.png',description:'Paul Atreides unites with Chani and the Fremen.',rating:'8.6',raw:{id:1,name:'Dune.Part.Two.2024.mkv'}},{id:'2',title:'House of the Dragon',type:'library',mediaType:'series',year:'2024',season:2,episode:3,poster:'assets/app-icon.png',background:'assets/brand-wide.png',raw:{id:2,name:'House.of.the.Dragon.S02E03.mkv'}},{id:'3',title:'A Readable Unmatched Release',type:'library',mediaType:'movie',year:'completed',poster:'',raw:{id:3,name:'A.Readable.Unmatched.Release.1080p.mkv'}}]);
 ipcMain.handle('library:play',()=>({ok:true,player:'embedded',url:'http://127.0.0.1:65530/media/'+('a'.repeat(64))}));
 ipcMain.handle('simkl:status',()=>({connected:false,clientId:''}));ipcMain.handle('clipboard:write',()=>({ok:true}));ipcMain.handle('tracking:toggle',()=>({tracked:true}));ipcMain.handle('tracking:mark-watched',()=>({ok:true,simklSynced:false}));
 const win=new BrowserWindow({width:1440,height:900,show:false,backgroundColor:'#070a12',webPreferences:{preload:path.join(__dirname,'..','src','preload.cjs'),contextIsolation:true}});await win.loadFile(path.join(__dirname,'..','src','index.html'));const dir=path.join(__dirname,'..','artifacts');fs.mkdirSync(dir,{recursive:true});
 for(const [type,file] of [['movie','movies-broad.png'],['series','series-broad.png'],['anime','anime-no-banner.png']]){await win.webContents.executeJavaScript(`document.querySelector('[data-section=${type}]').click()`);await delay(500);fs.writeFileSync(path.join(dir,file),(await win.webContents.capturePage()).toPNG())}
 await win.webContents.executeJavaScript("document.querySelector('[data-section=movie]').click()");await delay(600);await win.webContents.executeJavaScript("document.querySelector('#filterToggle')?.click();document.querySelector('[data-genre=\"Action\"]')?.click();const rating=document.querySelector('#ratingFilter');rating.value='8';rating.dispatchEvent(new Event('change'))");await delay(200);fs.writeFileSync(path.join(dir,'catalog-filters.png'),(await win.webContents.capturePage()).toPNG());
 await win.webContents.executeJavaScript("document.querySelector('[data-section=series]').click()");await delay(300);await win.webContents.executeJavaScript("document.querySelector('#featuredOpen')?.click()");await delay(300);fs.writeFileSync(path.join(dir,'episode-selector.png'),(await win.webContents.capturePage()).toPNG());
 await win.webContents.executeJavaScript("document.querySelector('[data-section=library]').click()");await delay(300);fs.writeFileSync(path.join(dir,'torbox-library.png'),(await win.webContents.capturePage()).toPNG());
 await win.webContents.executeJavaScript("document.querySelector('#appSettings').click()");await delay(300);fs.writeFileSync(path.join(dir,'settings-connections.png'),(await win.webContents.capturePage()).toPNG());await win.webContents.executeJavaScript("document.querySelector('.modal').scrollTop=document.querySelector('.modal').scrollHeight");await delay(150);fs.writeFileSync(path.join(dir,'settings-themes.png'),(await win.webContents.capturePage()).toPNG());await win.webContents.executeJavaScript("document.querySelector('[data-theme-choice=ember]').click()");await delay(200);fs.writeFileSync(path.join(dir,'theme-ember.png'),(await win.webContents.capturePage()).toPNG());await win.webContents.executeJavaScript("document.querySelector('#closeModal').click();document.querySelector('[data-section=library]').click()");await delay(300);await win.webContents.executeJavaScript("openPlayer({url:'http://127.0.0.1:65530/media/"+"a".repeat(64)+"'},'Dune: Part Two','2024 • 2h 46m',false)");await delay(250);fs.writeFileSync(path.join(dir,'embedded-player.png'),(await win.webContents.capturePage()).toPNG());win.destroy();app.exit(0);
});
