const ROOM_ALPHABET='ABCDEFGHJKLMNPQRSTUVWXYZ23456789';
function filterCatalog(items,section='home',query=''){const q=query.trim().toLowerCase();return items.filter(item=>(section==='home'||item.type===section)&&(!q||`${item.title} ${item.year}`.toLowerCase().includes(q)))}
function createRoomCode(random=Math.random){let value='';for(let i=0;i<6;i++)value+=ROOM_ALPHABET[Math.floor(random()*ROOM_ALPHABET.length)%ROOM_ALPHABET.length];return`${value.slice(0,3)}-${value.slice(3)}`}
function streamResolution(stream){const text=`${stream.name||''} ${stream.title||''}`.toLowerCase();if(/2160|4k/.test(text))return 2160;if(/1080/.test(text))return 1080;if(/720/.test(text))return 720;return stream.resolution||0}
function rankStreams(streams){const score=s=>(s.exact===false?0:100000)+(s.cached===false?0:20000)+(s.compatible===false?-50000:10000)+streamResolution(s);return[...streams].sort((a,b)=>score(b)-score(a))}
function validateTorBoxToken(token){return typeof token==='string'&&token.trim().length>=24&&!/\s/.test(token.trim())}
function meteorConfigPath(token){return Buffer.from(JSON.stringify({debridService:'torbox',debridApiKey:token,maxResults:'20',cachedOnly:true,allowP2P:false}),'utf8').toString('base64url')}
function meteorP2PConfigPath(){return Buffer.from(JSON.stringify({debridService:'torrent',debridApiKey:'',maxResults:'30',allowP2P:true}),'utf8').toString('base64url')}
function normalizeTrailers(values){return(values||[]).map(x=>typeof x==='string'?{source:x,type:'Trailer',name:'Trailer'}:{source:x.source||x.youtubeId||x.id||'',type:x.type||'Trailer',name:x.name||x.type||'Trailer'}).filter(x=>/^[\w-]{6,20}$/.test(x.source))}
function normalizeMeta(meta,fallbackType){return{id:meta.id||meta.imdb_id,title:meta.name||meta.title||'Untitled',type:fallbackType||meta.type,poster:meta.poster||'',background:meta.background||'',logo:meta.logo||'',year:String(meta.year||''),description:meta.description||'',rating:String(meta.imdbRating||meta.rating||''),runtime:String(meta.runtime||''),genres:Array.isArray(meta.genres)?meta.genres:Array.isArray(meta.genre)?meta.genre:[],videos:Array.isArray(meta.videos)?meta.videos:[],trailers:normalizeTrailers(meta.trailers||meta.trailerStreams)}}
function normalizeKitsuEpisode(record,parentId){const a=record.attributes||{},season=Number(a.seasonNumber)||1,episode=Number(a.number)||1;return{id:`${parentId}:${season}:${episode}`,season,episode,number:episode,title:a.canonicalTitle||a.titles?.en_us||a.titles?.en||`Episode ${episode}`,released:a.airdate||''}}
function normalizeKitsuAnime(record){const a=record.attributes||{},id=`kitsu:${record.id}`,count=Number(a.episodeCount)||0;return{id,title:a.canonicalTitle||a.titles?.en_us||a.titles?.en||'Untitled',type:'anime',poster:a.posterImage?.large||a.posterImage?.original||'',background:a.coverImage?.large||a.coverImage?.original||'',logo:'',year:String(a.startDate||'').slice(0,4),description:a.synopsis||a.description||'',rating:String(a.averageRating||''),runtime:a.episodeLength?`${a.episodeLength} min`:'',genres:Array.isArray(a.genres)?a.genres:[],videos:Array.from({length:count},(_,i)=>({id:`${id}:1:${i+1}`,season:1,episode:i+1,number:i+1,title:`Episode ${i+1}`,released:''})),trailers:normalizeTrailers(a.youtubeVideoId?[a.youtubeVideoId]:[])}}
function selectPlayableStream(streams){const playable=(streams||[]).filter(s=>typeof s.url==='string'&&/^https?:\/\//.test(s.url));return rankStreams(playable)[0]||null}
function selectVideoFile(files,season,episode){const video=/\.(mkv|mp4|avi|mov|webm|m4v|ts)$/i;const candidates=[...(files||[])].filter(f=>video.test(f.name||f.short_name||''));if(Number.isFinite(season)&&Number.isFinite(episode)){const s=String(season).padStart(2,'0'),e=String(episode).padStart(2,'0');const patterns=[new RegExp(`S${s}[ ._-]*E${e}`,'i'),new RegExp(`(?:^|[ ._-])${season}x${e}(?:[ ._-]|$)`,'i')];const match=candidates.filter(f=>patterns.some(p=>p.test(f.name||f.short_name||''))).sort((a,b)=>(b.size||0)-(a.size||0))[0];if(match)return match}return candidates.sort((a,b)=>(b.size||0)-(a.size||0))[0]||null}
module.exports={filterCatalog,createRoomCode,rankStreams,validateTorBoxToken,meteorConfigPath,meteorP2PConfigPath,normalizeMeta,normalizeKitsuAnime,normalizeKitsuEpisode,selectPlayableStream,selectVideoFile};
