const ROOM_ALPHABET='ABCDEFGHJKLMNPQRSTUVWXYZ23456789';
const {filterCatalog,isItemWatched,episodeWatchState,airingStatus}=require('./shared.js');
function createRoomCode(random=Math.random){let value='';for(let i=0;i<6;i++)value+=ROOM_ALPHABET[Math.floor(random()*ROOM_ALPHABET.length)%ROOM_ALPHABET.length];return`${value.slice(0,3)}-${value.slice(3)}`}
function streamResolution(stream){const text=`${stream.name||''} ${stream.title||''}`.toLowerCase();if(/2160|4k/.test(text))return 2160;if(/1080/.test(text))return 1080;if(/720/.test(text))return 720;return stream.resolution||0}
function rankStreams(streams){const score=s=>(s.exact===false?0:100000)+(s.cached===false?0:20000)+(s.compatible===false?-50000:10000)+streamResolution(s);return[...streams].sort((a,b)=>score(b)-score(a))}
function validateTorBoxToken(token){return typeof token==='string'&&token.trim().length>=24&&!/\s/.test(token.trim())}
function meteorConfigPath(token){return Buffer.from(JSON.stringify({debridService:'torbox',debridApiKey:token,maxResults:'20',cachedOnly:true,allowP2P:false}),'utf8').toString('base64url')}
function meteorP2PConfigPath(){return Buffer.from(JSON.stringify({debridService:'torrent',debridApiKey:'',maxResults:'30',allowP2P:true}),'utf8').toString('base64url')}
function normalizeTrailers(values){return(values||[]).map(x=>typeof x==='string'?{source:x,type:'Trailer',name:'Trailer'}:{source:x.source||x.youtubeId||x.id||'',type:x.type||'Trailer',name:x.name||x.type||'Trailer'}).filter(x=>/^[\w-]{6,20}$/.test(x.source))}
function normalizeMeta(meta,fallbackType){return{id:meta.id||meta.imdb_id,title:meta.name||meta.title||'Untitled',type:fallbackType||meta.type,poster:meta.poster||'',background:meta.background||'',logo:meta.logo||'',year:String(meta.year||''),status:meta.status||'',description:meta.description||'',rating:String(meta.imdbRating||meta.rating||''),runtime:String(meta.runtime||''),genres:Array.isArray(meta.genres)?meta.genres:Array.isArray(meta.genre)?meta.genre:[],videos:Array.isArray(meta.videos)?meta.videos:[],trailers:normalizeTrailers(meta.trailers||meta.trailerStreams)}}
function normalizeKitsuEpisode(record,parentId){const a=record.attributes||{},season=Number(a.seasonNumber)||1,episode=Number(a.number)||1;return{id:`${parentId}:${season}:${episode}`,season,episode,number:episode,title:a.canonicalTitle||a.titles?.en_us||a.titles?.en||`Episode ${episode}`,released:a.airdate||''}}
function normalizeKitsuAnime(record){const a=record.attributes||{},id=`kitsu:${record.id}`,count=Number(a.episodeCount)||0;return{id,title:a.canonicalTitle||a.titles?.en_us||a.titles?.en||'Untitled',type:'anime',poster:a.posterImage?.large||a.posterImage?.original||'',background:a.coverImage?.large||a.coverImage?.original||'',logo:'',year:String(a.startDate||'').slice(0,4),status:a.status||'',description:a.synopsis||a.description||'',rating:String(a.averageRating||''),runtime:a.episodeLength?`${a.episodeLength} min`:'',genres:Array.isArray(a.genres)?a.genres:[],videos:Array.from({length:count},(_,i)=>({id:`${id}:1:${i+1}`,season:1,episode:i+1,number:i+1,title:`Episode ${i+1}`,released:''})),trailers:normalizeTrailers(a.youtubeVideoId?[a.youtubeVideoId]:[])}}
function normalizeSimklCatalog(item,type){const year=String(item.release_date||'').match(/\d{4}/)?.[0]||String(item.year||''),poster=item.poster?`https://simkl.in/posters/${item.poster}_m.jpg`:'',background=item.fanart?`https://simkl.in/fanart/${item.fanart}_medium.jpg`:'';return{id:item.ids?.imdb||`simkl:${item.ids?.simkl_id}`,simklId:item.ids?.simkl_id,title:item.title||'Untitled',type,poster,background,logo:'',year,description:item.overview||'',rating:String(item.ratings?.imdb?.rating||item.ratings?.simkl?.rating||''),runtime:String(item.runtime||''),genres:Array.isArray(item.genres)?item.genres:[],videos:[],trailers:normalizeTrailers(item.trailer?[item.trailer]:[])}}
function normalizeSimklSearchResult(item,type){const poster=item.poster?`https://simkl.in/posters/${item.poster}_m.jpg`:'';return{id:`simkl:${item.ids?.simkl_id}`,title:item.title||'Untitled',type,poster,background:'',logo:'',year:String(item.year||''),description:'',rating:String(item.ratings?.imdb?.rating||item.ratings?.simkl?.rating||''),runtime:'',genres:[],videos:[],trailers:[]}}
const FRANCHISE_ANIME_ROLES=new Set(['sequel','prequel','side_story','spin_off','parent_story','alternative_version','alternative_setting','full_story','summary']);
function filterAnimeRelationships(payload={}){const included=new Map((payload.included||[]).filter(x=>x.type==='anime').map(x=>[String(x.id),x]));const entries=[];for(const rel of payload.data||[]){const role=rel.attributes?.role;if(!FRANCHISE_ANIME_ROLES.has(role))continue;const destId=rel.relationships?.destination?.data?.id;const dest=destId!==undefined?included.get(String(destId)):null;if(!dest)continue;entries.push(normalizeKitsuAnime(dest))}return entries}
function normalizeTmdbCollectionPart(part,imdbId){return{id:imdbId,type:'movie',title:part.title||part.original_title||'Untitled',poster:part.poster_path?`https://image.tmdb.org/t/p/w500${part.poster_path}`:'',background:'',logo:'',year:String(part.release_date||'').slice(0,4),description:part.overview||'',rating:String(part.vote_average||''),runtime:'',genres:[],videos:[],trailers:[]}}
function readableTitle(value){const words=value.replace(/[._]+/g,' ').replace(/\[[^\]]*]|\([^)]*\)/g,' ').replace(/\s+/g,' ').trim().split(' ');const loud=words.join('').toUpperCase()===words.join('')||words.join('').toLowerCase()===words.join('');return words.map((word,index)=>{if(!loud)return word;const lower=word.toLowerCase();if(index&&['a','an','and','at','for','in','of','on','or','the','to'].includes(lower))return lower;return lower.charAt(0).toUpperCase()+lower.slice(1)}).join(' ')}
function parseReleaseName(value){let name=String(value||'').split(/[\\/]/).pop().replace(/\.(mkv|mp4|avi|mov|webm|m4v|ts)$/i,''),season=null,episode=null,year='';const ep=name.match(/(?:^|[ ._-])S(\d{1,2})[ ._-]*E(\d{1,3})/i)||name.match(/(?:^|[ ._-])(\d{1,2})x(\d{1,3})(?:[ ._-]|$)/i);if(ep){season=Number(ep[1]);episode=Number(ep[2]);name=name.slice(0,ep.index)}else{const years=[...name.matchAll(/(?:^|[ ._-])((?:19|20)\d{2})(?=[ ._-]|$)/g)];const match=years.at(-1);if(match&&match.index>0){year=match[1];name=name.slice(0,match.index)}}name=name.replace(/(?:^|[ ._-])(2160p|1080p|720p|480p|uhd|bluray|brrip|webrip|web-dl|web|hdtv|remux|x26[45]|h26[45]|hevc|av1|aac|ddp?\d(?:\.\d)?|dts|atmos).*$/i,'');return{title:readableTitle(name)||'Untitled',year,season,episode}}
function librarySourceName(raw){const files=raw.files||raw.file_list||[];return raw.name||raw.filename||files.find(f=>/\.(mkv|mp4|avi|mov|webm|m4v|ts)$/i.test(f.name||f.short_name||''))?.name||'Untitled'}
function mediaKey(value){return String(value||'').normalize('NFKD').replace(/[^a-z0-9]/gi,'').toLowerCase()}
function enrichTorBoxItem(raw,catalog=[]){const parsed=parseReleaseName(librarySourceName(raw)),key=mediaKey(parsed.title),matches=catalog.filter(x=>mediaKey(x.title)===key),match=matches.find(x=>!parsed.year||String(x.year)===parsed.year)||matches[0];return{id:String(raw.id||raw.torrent_id||raw.hash||librarySourceName(raw)),title:match?.title||parsed.title,type:'library',mediaType:match?.type||(parsed.season?'series':'movie'),year:match?.year||parsed.year||raw.download_state||raw.state||'',season:parsed.season,episode:parsed.episode,poster:match?.poster||raw.poster||'',background:match?.background||raw.background||'',description:match?.description||'',rating:match?.rating||'',runtime:match?.runtime||'',genres:match?.genres||[],metadataId:match?.id||'',raw}}
function selectPlayableStream(streams){const playable=(streams||[]).filter(s=>typeof s.url==='string'&&/^https?:\/\//.test(s.url));return rankStreams(playable)[0]||null}
function selectVideoFile(files,season,episode){const video=/\.(mkv|mp4|avi|mov|webm|m4v|ts)$/i;const candidates=[...(files||[])].filter(f=>video.test(f.name||f.short_name||''));if(Number.isFinite(season)&&Number.isFinite(episode)){const s=String(season).padStart(2,'0'),e=String(episode).padStart(2,'0');const patterns=[new RegExp(`S${s}[ ._-]*E${e}`,'i'),new RegExp(`(?:^|[ ._-])${season}x${e}(?:[ ._-]|$)`,'i')];const match=candidates.filter(f=>patterns.some(p=>p.test(f.name||f.short_name||''))).sort((a,b)=>(b.size||0)-(a.size||0))[0];if(match)return match}return candidates.sort((a,b)=>(b.size||0)-(a.size||0))[0]||null}

function dedupeCatalog(groups){const seen=new Set(),result=[];for(const item of(groups||[]).flat()){const key=String(item?.id||'');if(!key||seen.has(key))continue;seen.add(key);result.push(item)}return result}
function lastWatchedAt(history,contentId){let latest='';for(const h of history||[]){if(String(h.id)!==String(contentId)||!h.watchedAt)continue;if(!latest||new Date(h.watchedAt)>new Date(latest))latest=h.watchedAt}return latest}
function continueWatchingList(details,history){const rows=[];for(const detail of details||[]){const episodes=(detail.videos||[]).filter(v=>(v.season??1)>0).sort((a,b)=>(a.season||1)-(b.season||1)||(a.episode||a.number||0)-(b.episode||b.number||0));if(!episodes.length)continue;const progress=episodeWatchState(episodes,history,detail.id);if(progress.watchedCount===0||progress.watchedCount>=progress.total)continue;const next=episodes[progress.nextIndex>=0?progress.nextIndex:0];rows.push({...detail,continueSeason:next.season||1,continueEpisode:next.episode||next.number||1,watchedCount:progress.watchedCount,totalCount:progress.total,lastWatchedAt:lastWatchedAt(history,detail.id)})}return rows.sort((a,b)=>new Date(b.lastWatchedAt)-new Date(a.lastWatchedAt))}
module.exports={filterCatalog,isItemWatched,dedupeCatalog,episodeWatchState,airingStatus,continueWatchingList,createRoomCode,rankStreams,validateTorBoxToken,meteorConfigPath,meteorP2PConfigPath,normalizeMeta,normalizeKitsuAnime,normalizeKitsuEpisode,normalizeSimklCatalog,normalizeSimklSearchResult,filterAnimeRelationships,normalizeTmdbCollectionPart,parseReleaseName,enrichTorBoxItem,selectPlayableStream,selectVideoFile};
