const {DatabaseSync}=require('node:sqlite');
function parse(value,fallback){try{return JSON.parse(value)}catch{return fallback}}
function normalizeTitle(item){return{id:String(item.id),simklId:item.simklId||null,type:item.type||'movie',title:item.title||item.name||'Untitled',poster:item.poster||'',background:item.background||'',logo:item.logo||'',year:String(item.year||''),genres:Array.isArray(item.genres)?item.genres:[],description:item.description||'',rating:item.rating||'',runtime:item.runtime||'',trailers:Array.isArray(item.trailers)?item.trailers:[]}}
function episodePosition(v){return{season:Number(v.season)||1,episode:Number(v.episode??v.number)||0}}
function compareEpisode(a,b){return a.season-b.season||a.episode-b.episode}
function latestReleased(videos,now){return(videos||[]).filter(v=>{const released=v.released||v.firstAired;return !released||new Date(released)<=now}).map(episodePosition).filter(v=>v.episode>0).sort(compareEpisode).at(-1)||{season:0,episode:0}}
function createDatabase(filename){
 const sql=new DatabaseSync(filename);sql.exec('PRAGMA journal_mode = WAL');sql.exec('PRAGMA foreign_keys = ON');
 sql.exec(`CREATE TABLE IF NOT EXISTS tracked(content_id TEXT PRIMARY KEY,type TEXT NOT NULL,title TEXT NOT NULL,poster TEXT,metadata_json TEXT NOT NULL,tracked_at TEXT NOT NULL,baseline_season INTEGER NOT NULL DEFAULT 0,baseline_episode INTEGER NOT NULL DEFAULT 0);CREATE TABLE IF NOT EXISTS watch_history(watch_key TEXT PRIMARY KEY,content_id TEXT NOT NULL,type TEXT NOT NULL,title TEXT NOT NULL,season INTEGER,episode INTEGER,watched_at TEXT NOT NULL,metadata_json TEXT NOT NULL);CREATE TABLE IF NOT EXISTS catalog_cache(cache_key TEXT PRIMARY KEY,payload_json TEXT NOT NULL,expires_at INTEGER NOT NULL,updated_at INTEGER NOT NULL);CREATE INDEX IF NOT EXISTS idx_history_content ON watch_history(content_id,watched_at DESC);`);
 const columns=new Set(sql.prepare('PRAGMA table_info(tracked)').all().map(x=>x.name));if(!columns.has('baseline_season'))sql.exec('ALTER TABLE tracked ADD COLUMN baseline_season INTEGER NOT NULL DEFAULT 0');if(!columns.has('baseline_episode'))sql.exec('ALTER TABLE tracked ADD COLUMN baseline_episode INTEGER NOT NULL DEFAULT 0');
 const q={track:sql.prepare(`INSERT INTO tracked(content_id,type,title,poster,metadata_json,tracked_at,baseline_season,baseline_episode) VALUES(@id,@type,@title,@poster,@json,@now,@baselineSeason,@baselineEpisode) ON CONFLICT(content_id) DO UPDATE SET type=excluded.type,title=excluded.title,poster=excluded.poster,metadata_json=excluded.metadata_json`),untrack:sql.prepare('DELETE FROM tracked WHERE content_id=?'),isTracked:sql.prepare('SELECT 1 FROM tracked WHERE content_id=?'),tracked:sql.prepare('SELECT metadata_json FROM tracked ORDER BY tracked_at DESC'),trackedRows:sql.prepare('SELECT content_id,metadata_json,baseline_season,baseline_episode FROM tracked ORDER BY tracked_at DESC'),watched:sql.prepare(`INSERT INTO watch_history(watch_key,content_id,type,title,season,episode,watched_at,metadata_json) VALUES(@key,@id,@type,@title,@season,@episode,@now,@json) ON CONFLICT(watch_key) DO UPDATE SET watched_at=excluded.watched_at,metadata_json=excluded.metadata_json`),history:sql.prepare('SELECT metadata_json,season,episode,watched_at FROM watch_history ORDER BY watched_at DESC'),putCache:sql.prepare(`INSERT INTO catalog_cache(cache_key,payload_json,expires_at,updated_at) VALUES(?,?,?,?) ON CONFLICT(cache_key) DO UPDATE SET payload_json=excluded.payload_json,expires_at=excluded.expires_at,updated_at=excluded.updated_at`),getCache:sql.prepare('SELECT payload_json,expires_at FROM catalog_cache WHERE cache_key=?'),lastEpisode:sql.prepare('SELECT season,episode FROM watch_history WHERE content_id=? AND season IS NOT NULL ORDER BY season DESC,episode DESC LIMIT 1')};
 function fail(error){throw new Error('Local database error: '+error.message)}
 const db={
  track(item,now=new Date()){try{const value=normalizeTitle(item),baseline=latestReleased(item.videos,now);q.track.run({id:value.id,type:value.type,title:value.title,poster:value.poster,json:JSON.stringify(value),now:now.toISOString(),baselineSeason:baseline.season,baselineEpisode:baseline.episode});return value}catch(error){return fail(error)}},
  untrack(id){try{return q.untrack.run(String(id)).changes>0}catch(error){return fail(error)}},
  isTracked(id){try{return Boolean(q.isTracked.get(String(id)))}catch(error){return fail(error)}},
  tracked(){try{return q.tracked.all().map(r=>parse(r.metadata_json,{}))}catch(error){return fail(error)}},
  markWatched(item,playback={}){try{const value=normalizeTitle(item),season=Number.isFinite(playback.season)?playback.season:null,episode=Number.isFinite(playback.episode)?playback.episode:null,key=`${value.id}:${season??'movie'}:${episode??'movie'}`;q.watched.run({key,id:value.id,type:value.type,title:value.title,season,episode,now:new Date().toISOString(),json:JSON.stringify(value)});return value}catch(error){return fail(error)}},
  history(){try{return q.history.all().map(r=>({...parse(r.metadata_json,{}),season:r.season,episode:r.episode,watchedAt:r.watched_at}))}catch(error){return fail(error)}},
  preferredGenres(limit=3){const counts=new Map();for(const item of db.history())for(const genre of item.genres||[])counts.set(genre,(counts.get(genre)||0)+1);return[...counts].sort((a,b)=>b[1]-a[1]||a[0].localeCompare(b[0])).slice(0,limit).map(x=>x[0])},
  putCache(key,payload,ttlMs){try{const now=Date.now();q.putCache.run(key,JSON.stringify(payload),now+ttlMs,now)}catch{}},
  getCache(key,{allowExpired=false}={}){try{const row=q.getCache.get(key);return row&&(allowExpired||row.expires_at>Date.now())?parse(row.payload_json,null):null}catch{return null}},
  trackedUpdates(details,now=new Date()){try{const byId=new Map(details.map(x=>[String(x.id),x])),updates=[];for(const row of q.trackedRows.all()){const tracked=parse(row.metadata_json,{}),detail=byId.get(String(row.content_id));if(!detail)continue;const watched=q.lastEpisode.get(row.content_id)||{season:0,episode:0},baseline={season:row.baseline_season||0,episode:row.baseline_episode||0},last=compareEpisode(watched,baseline)>=0?watched:baseline;const released=(detail.videos||[]).filter(v=>{const p=episodePosition(v),date=v.released||v.firstAired;return(!date||new Date(date)<=now)&&compareEpisode(p,last)>0});if(released.length)updates.push({...tracked,newEpisodeCount:released.length,latestEpisode:released.at(-1)})}return updates}catch(error){return fail(error)}},
  close(){sql.close()},filename
 };
 return db
}
module.exports={createDatabase};
