const {app,BrowserWindow,ipcMain,safeStorage,shell,clipboard}=require('electron');
const path=require('node:path');const fs=require('node:fs');
const {pathToFileURL}=require('node:url');
const crypto=require('node:crypto');const http=require('node:http');
const {validateTorBoxToken,meteorP2PConfigPath,normalizeMeta,normalizeKitsuAnime,normalizeSimklCatalog,normalizeSimklSearchResult,filterAnimeRelationships,normalizeTmdbCollectionPart,dedupeCatalog,enrichTorBoxItem,rankStreams,selectVideoFile,continueWatchingList,airingStatus}=require('./core.cjs');
const {createDatabase}=require('./database.cjs');
const {historyPayload,seasonHistoryPayload,scrobblePayload,watchedFromAllItems}=require('./simkl.cjs');
const {buildAuthorizeUrl,normalizeMalEntry,localWatchedEpisodeCounts,computeReconciliation}=require('./mal.cjs');
const {buildSearchParams,normalizeSubtitleResult,srtToVtt}=require('./opensubtitles.cjs');
const {createPlaybackProxy}=require('./playback.cjs');
const {createVlcTranscoder,findFfprobe,findFfmpeg,findVlc,probeMedia,needsAudioCompatibility,captureFrame}=require('./vlc.cjs');
const {THEMES,normalizeTheme,publicSettings,logoutSettings}=require('./preferences.cjs');
const {isAllowedExternalUrl,isValidCatalogKind,isTrustedIpcSender,sanitizeTrackers}=require('./security.cjs');
const {autoUpdater}=require('electron-updater');
const TORBOX='https://api.torbox.app/v1/api';
const OS_API='https://api.opensubtitles.com/api/v1';
function osUserAgent(){return`r3v07v3r-media-hub v${app.getVersion()}`}
const MAL_REDIRECT_PORT=48765,MAL_REDIRECT_URI=`http://127.0.0.1:${MAL_REDIRECT_PORT}/mal/callback`;
let malPendingServer=null;
let mediaDb,activeMediaUrl='',activeMediaTracks={video:[],audio:[],subtitle:[],probed:false},updateReady=false,activeSubtitlePath='';const playbackProxy=createPlaybackProxy(),vlcTranscoder=createVlcTranscoder({onLog:line=>logError('vlc:stderr',redactUrls(line.trim()))}),ffprobePath=findFfprobe(),ffmpegPath=findFfmpeg(),vlcInstallPath=findVlc();
function subtitleCacheDir(){return path.join(app.getPath('userData'),'subtitles-cache')}
function clearActiveSubtitle(){if(activeSubtitlePath){try{fs.unlinkSync(activeSubtitlePath)}catch{}activeSubtitlePath=''}}
const settingsPath=()=>path.join(app.getPath('userData'),'settings.json');
const logPath=()=>path.join(app.getPath('userData'),'logs','main.log');
function logError(scope,error){try{const line=`${new Date().toISOString()} [${scope}] ${error?.message||error}\n`;fs.mkdirSync(path.dirname(logPath()),{recursive:true});fs.appendFileSync(logPath(),line)}catch{}}
function redactUrls(value){return String(value).replace(/https?:\/\/\S+/gi,'[redacted-url]')}
function readSettings(){try{return JSON.parse(fs.readFileSync(settingsPath(),'utf8'))}catch{return{}}}
function writeSettings(v){const target=settingsPath(),directory=path.dirname(target),temporary=`${target}.${process.pid}.${Date.now()}.tmp`;fs.mkdirSync(directory,{recursive:true});try{fs.writeFileSync(temporary,JSON.stringify(v,null,2),{mode:0o600});fs.renameSync(temporary,target)}finally{try{if(fs.existsSync(temporary))fs.unlinkSync(temporary)}catch{}}}
function encrypt(v){if(!safeStorage.isEncryptionAvailable())throw new Error('Windows secure storage is unavailable.');return safeStorage.encryptString(v).toString('base64')}
function decrypt(v){try{return safeStorage.decryptString(Buffer.from(v,'base64'))}catch{return''}}
function token(){const settings=readSettings();return settings.onboardingVersion===2?decrypt(settings.torboxToken||''):''}
function simklCredentials(){const s=readSettings();return{clientId:s.simklClientId||'',accessToken:decrypt(s.simklAccessToken||'')}}
function malCredentials(){const s=readSettings();return{clientId:s.malClientId||'',clientSecret:decrypt(s.malClientSecret||''),accessToken:decrypt(s.malAccessToken||''),refreshToken:decrypt(s.malRefreshToken||''),expiresAt:Number(s.malTokenExpiresAt)||0}}
function malTokenRequest(params){return getJson('https://myanimelist.net/v1/oauth2/token',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:new URLSearchParams(params)})}
async function malEnsureToken(){const creds=malCredentials();if(!creds.accessToken)throw new Error('MyAnimeList is not connected.');if(creds.expiresAt-Date.now()>5*60*1000)return creds.accessToken;if(!creds.refreshToken)throw new Error('MyAnimeList session expired. Reconnect in Settings.');const params={client_id:creds.clientId,grant_type:'refresh_token',refresh_token:creds.refreshToken};if(creds.clientSecret)params.client_secret=creds.clientSecret;const result=await malTokenRequest(params);const s=readSettings();s.malAccessToken=encrypt(result.access_token);s.malRefreshToken=encrypt(result.refresh_token||creds.refreshToken);s.malTokenExpiresAt=Date.now()+(Number(result.expires_in)||3600)*1000;writeSettings(s);return result.access_token}
async function malRequest(pathname,options={}){const accessToken=await malEnsureToken();return getJson(`https://api.myanimelist.net/v2${pathname}`,{...options,headers:{Authorization:`Bearer ${accessToken}`,'User-Agent':`r3v07v3r-media-hub/${app.getVersion()}`,...options.headers}})}
async function resolveKitsuIdForMal(malId){const key=`mal:mapping:kitsu-for-mal:${malId}`,cached=mediaDb.getCache(key);if(cached!==null)return cached;try{const result=await getJson(`https://kitsu.io/api/edge/anime?filter[mappingExternalId]=${encodeURIComponent(malId)}&filter[mappingExternalSite]=myanimelist/anime`),kitsuId=result.data?.[0]?.id?`kitsu:${result.data[0].id}`:'';mediaDb.putCache(key,kitsuId,30*24*60*60*1000);return kitsuId}catch{return''}}
async function resolveMalIdForKitsu(kitsuId){const numericId=String(kitsuId).replace(/^kitsu:/,'').split(':')[0],key=`mal:mapping:mal-for-kitsu:${numericId}`,cached=mediaDb.getCache(key);if(cached!==null)return cached;try{const result=await getJson(`https://kitsu.io/api/edge/anime/${encodeURIComponent(numericId)}/mappings`),match=(result.data||[]).find(m=>m.attributes?.externalSite==='myanimelist/anime'),malId=match?Number(match.attributes.externalId)||0:0;mediaDb.putCache(key,malId,30*24*60*60*1000);return malId}catch{return 0}}
async function pushMalProgress(item){if(item.type!=='anime'||!String(item.id).startsWith('kitsu:'))return{malSynced:false};if(!malCredentials().accessToken)return{malSynced:false};try{const malId=await resolveMalIdForKitsu(item.id);if(!malId)return{malSynced:false};const counts=localWatchedEpisodeCounts(mediaDb.history()),watchedEpisodes=counts[item.id]||0;await malRequest(`/anime/${malId}/my_list_status`,{method:'PATCH',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:new URLSearchParams({num_watched_episodes:String(watchedEpisodes)})});return{malSynced:true}}catch(error){logError('mal:push-progress',error);return{malSynced:false,malError:error.message}}}
async function fetchAllMalAnimeList(){const entries=[];let pathname='/users/@me/animelist?fields=list_status&limit=1000';for(let page=0;page<10&&pathname;page++){const result=await malRequest(pathname);entries.push(...(result.data||[]));pathname=result.paging?.next?result.paging.next.replace('https://api.myanimelist.net/v2',''):null}return entries}
function stopMalServer(){if(malPendingServer){try{malPendingServer.close()}catch{}malPendingServer=null}}
function waitForMalCallback(expectedState,timeoutMs=120000){return new Promise((resolve,reject)=>{stopMalServer();const server=http.createServer((req,res)=>{try{const url=new URL(req.url,'http://127.0.0.1');if(url.pathname!=='/mal/callback'){res.writeHead(404);res.end();return}const code=url.searchParams.get('code'),state=url.searchParams.get('state'),error=url.searchParams.get('error');res.writeHead(200,{'Content-Type':'text/html'});res.end('<html><body style="font-family:sans-serif;text-align:center;padding:40px"><h2>You can close this tab</h2><p>Return to R3 Media Hub to continue.</p></body></html>');clearTimeout(timer);stopMalServer();if(error)return reject(new Error(`MyAnimeList authorization was denied: ${error}`));if(!state||state!==expectedState)return reject(new Error('MyAnimeList authorization state mismatch.'));if(!code)return reject(new Error('MyAnimeList did not return an authorization code.'));resolve(code)}catch(error){reject(error)}});malPendingServer=server;const timer=setTimeout(()=>{stopMalServer();reject(new Error('MyAnimeList authorization timed out.'))},timeoutMs);server.once('error',error=>{clearTimeout(timer);malPendingServer=null;reject(new Error(error.code==='EADDRINUSE'?`Port ${MAL_REDIRECT_PORT} is already in use. Close whatever is using it and try again.`:error.message))});server.listen(MAL_REDIRECT_PORT,'127.0.0.1')})}
function tmdbCredentials(){const s=readSettings();return{apiKey:decrypt(s.tmdbApiKey||'')}}
function osCredentials(){const s=readSettings();return{apiKey:decrypt(s.osApiKey||''),username:decrypt(s.osUsername||''),password:decrypt(s.osPassword||''),token:decrypt(s.osToken||'')}}
function osConnected(){const c=osCredentials();return Boolean(c.apiKey&&c.username&&c.password)}
async function osLoginWith(apiKey,username,password){const result=await getJson(`${OS_API}/login`,{method:'POST',headers:{'Content-Type':'application/json','Api-Key':apiKey,'User-Agent':osUserAgent()},body:JSON.stringify({username,password})});if(!result.token)throw new Error('OpenSubtitles login failed.');return result.token}
async function osRequest(pathname,options={}){const creds=osCredentials();if(!creds.apiKey||!creds.username||!creds.password)throw new Error('OpenSubtitles is not connected.');let token=creds.token;if(!token){token=await osLoginWith(creds.apiKey,creds.username,creds.password);const s=readSettings();s.osToken=encrypt(token);writeSettings(s)}const call=tok=>getJson(`${OS_API}${pathname}`,{...options,headers:{'Api-Key':creds.apiKey,'User-Agent':osUserAgent(),Authorization:`Bearer ${tok}`,...options.headers}});try{return await call(token)}catch(error){if(error.status!==401)throw error;token=await osLoginWith(creds.apiKey,creds.username,creds.password);const s=readSettings();s.osToken=encrypt(token);writeSettings(s);return await call(token)}}
async function osDownloadSubtitleText(fileId){const result=await osRequest('/download',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({file_id:fileId})});if(!result.link)throw new Error('OpenSubtitles did not return a download link.');const response=await fetch(result.link);if(!response.ok)throw new Error('Could not download the subtitle file.');return response.text()}
async function preparePlayback(url){activeMediaUrl=url;await vlcTranscoder.stop();activeMediaTracks=await probeMedia(ffprobePath,url);if(needsAudioCompatibility(activeMediaTracks)&&vlcInstallPath){await playbackProxy.close();return{ok:true,player:'embedded',tracks:activeMediaTracks,autoReason:'Audio was converted for browser compatibility.',...await vlcTranscoder.start(vlcInstallPath,url,{audio:activeMediaTracks.audio.find(x=>x.default)?.ordinal??0})}}return{ok:true,player:'embedded',compatibility:false,tracks:activeMediaTracks,url:await playbackProxy.register(url)}}
async function stopPlayback(){activeMediaUrl='';activeMediaTracks={video:[],audio:[],subtitle:[],probed:false};clearActiveSubtitle();await Promise.all([playbackProxy.close(),vlcTranscoder.stop()])}
let activeWindow=null;
function clearTorBoxToken(){const s=readSettings();if(!s.torboxToken)return;delete s.torboxToken;writeSettings(s);if(activeWindow&&!activeWindow.isDestroyed())activeWindow.webContents.send('torbox:unauthorized')}
async function getJson(url,options={}){const controller=new AbortController();const timer=setTimeout(()=>controller.abort(),30000);try{const response=await fetch(url,{...options,signal:controller.signal});const body=await response.json().catch(()=>({}));if(response.status===401&&String(url).startsWith(TORBOX))clearTorBoxToken();if(!response.ok||body.success===false){const error=new Error(body.detail||`Request failed (${response.status})`);error.status=response.status;throw error}return body}finally{clearTimeout(timer)}}
async function torbox(pathname,query={}){const auth=token();if(!auth)throw new Error('TorBox is not connected.');const url=new URL(TORBOX+pathname);Object.entries(query).forEach(([k,v])=>v!==undefined&&url.searchParams.set(k,String(v)));return getJson(url,{headers:{Authorization:`Bearer ${auth}`}})}
const catalogUrls={movie:'https://v3-cinemeta.strem.io/catalog/movie/top.json',series:'https://v3-cinemeta.strem.io/catalog/series/top.json'};
async function kitsuCategories(id){const key=`kitsu:categories:${id}`,cached=mediaDb.getCache(key);if(cached)return cached;const result=await getJson(`https://kitsu.io/api/edge/anime/${encodeURIComponent(id)}/categories?page%5Blimit%5D=20`),genres=(result.data||[]).map(x=>x.attributes?.title).filter(Boolean);mediaDb.putCache(key,genres,7*24*60*60*1000);return genres}
async function simklCatalog(kind){const section=kind==='series'?'tv':'movies',feeds=await Promise.all(['week','month'].map(span=>getJson(`https://data.simkl.in/discover/trending/${section}/${span}_500.json`)));return dedupeCatalog(feeds.map(result=>(result||[]).map(x=>normalizeSimklCatalog(x,kind)).filter(x=>x.id&&!x.id.startsWith('simkl:'))))}
async function kitsuPage(offset){const result=await getJson(`https://kitsu.io/api/edge/anime?sort=-userCount&page%5Blimit%5D=20&page%5Boffset%5D=${offset}&include=categories`),categories=new Map((result.included||[]).filter(x=>x.type==='categories').map(x=>[String(x.id),x.attributes?.title]));return(result.data||[]).map(record=>({...record,attributes:{...record.attributes,genres:(record.relationships?.categories?.data||[]).map(x=>categories.get(String(x.id))).filter(Boolean)}})).map(normalizeKitsuAnime)}
async function kitsuCatalog(){const pages=[];for(let offset=0;offset<1000;offset+=100){pages.push(...await Promise.all([0,20,40,60,80].map(step=>kitsuPage(offset+step))));if(offset<900)await new Promise(resolve=>setTimeout(resolve,350))}return dedupeCatalog(pages)}
async function catalogData(kind,force=false){if(!['movie','series','anime'].includes(kind))throw new Error('Unknown catalog.');const key=`catalog:v2:${kind}`;if(!force){const cached=mediaDb.getCache(key);if(cached)return cached}let items;try{items=kind==='anime'?await kitsuCatalog():await simklCatalog(kind);if(!items.length)throw new Error('The broad catalog returned no titles.')}catch(primaryError){if(kind!=='anime')try{const result=await getJson(catalogUrls[kind]);items=(result.metas||[]).map(x=>normalizeMeta(x,kind))}catch{items=null}if(!items?.length){const stale=mediaDb.getCache(key,{allowExpired:true});if(stale?.length)return stale;throw primaryError}}mediaDb.putCache(key,items,6*60*60*1000);return items}
function simklEpisode(record,parentId){return{id:`${parentId}:${record.season||1}:${record.episode||1}`,season:Number(record.season)||1,episode:Number(record.episode)||1,number:Number(record.episode)||1,title:record.title||`Episode ${record.episode||1}`,released:record.date||'',description:record.description||'',thumbnail:record.img?`https://simkl.in/episodes/${record.img}_w.jpg`:''}}
function simklUrl(pathname,clientId){const url=new URL(pathname,'https://api.simkl.com');url.searchParams.set('client_id',clientId);url.searchParams.set('app-name','r3v07v3r-media-hub');url.searchParams.set('app-version',app.getVersion());return url.toString()}
async function simklRequest(pathname,options={}){const{clientId,accessToken}=simklCredentials();if(!clientId||!accessToken)throw new Error('Simkl is not connected.');return getJson(simklUrl(pathname,clientId),{...options,headers:{'Content-Type':'application/json',Authorization:`Bearer ${accessToken}`,'User-Agent':`r3v07v3r-media-hub/${app.getVersion()}`,...options.headers}})}
async function simklPublicRequest(pathname,options={}){const{clientId}=simklCredentials();if(!clientId)throw new Error('Add a Simkl Client ID in Settings to search movies & series.');return getJson(simklUrl(pathname,clientId),{...options,headers:{'User-Agent':`r3v07v3r-media-hub/${app.getVersion()}`,...options.headers}})}
async function resolveSimklId(type,simklId){const endpointType=type==='series'?'tv':'movies';const result=await simklPublicRequest(`/${endpointType}/${encodeURIComponent(simklId)}?extended=full`);const imdb=result?.ids?.imdb;if(!imdb)throw new Error('This title could not be matched to a playable source.');return imdb}
async function metadata(type,id){const resolvedId=String(id).startsWith('simkl:')?await resolveSimklId(type,String(id).slice(6)):id;const cacheKey=`meta:v3:${type}:${resolvedId}`,cached=mediaDb.getCache(cacheKey);if(cached)return cached;let item;try{if(type==='anime'){const kitsuId=String(resolvedId).replace(/^kitsu:/,'').split(':')[0],[result,genres]=await Promise.all([getJson(`https://kitsu.io/api/edge/anime/${encodeURIComponent(kitsuId)}`),kitsuCategories(kitsuId)]);item=normalizeKitsuAnime({...result.data,attributes:{...result.data?.attributes,genres}})}else{const result=await getJson(`https://v3-cinemeta.strem.io/meta/${type}/${encodeURIComponent(resolvedId)}.json`);item=normalizeMeta(result.meta||{},type)}}catch(primaryError){const source=(mediaDb.getCache(`catalog:v2:${type}`,{allowExpired:true})||[]).find(x=>String(x.id)===String(resolvedId));if(!source)throw primaryError;item={...source,videos:[]};if(type==='series'&&source.simklId){const episodes=await getJson(`https://api.simkl.com/tv/episodes/${encodeURIComponent(source.simklId)}`);item.videos=(episodes||[]).map(x=>simklEpisode(x,resolvedId))}}mediaDb.putCache(cacheKey,item,24*60*60*1000);return item}
async function kitsuSearch(query){const result=await getJson(`https://kitsu.io/api/edge/anime?filter%5Btext%5D=${encodeURIComponent(query)}&page%5Blimit%5D=20`);return(result.data||[]).map(normalizeKitsuAnime)}
async function simklSearch(kind,query){const endpointType=kind==='series'?'tv':'movie';const result=await simklPublicRequest(`/search/${endpointType}?q=${encodeURIComponent(query)}&extended=full`);return(Array.isArray(result)?result:[]).map(x=>normalizeSimklSearchResult(x,kind))}
async function relatedAnime(id){const key=`related:v1:anime:${id}`,cached=mediaDb.getCache(key);if(cached)return cached;try{const kitsuId=String(id).replace(/^kitsu:/,'').split(':')[0],result=await getJson(`https://kitsu.io/api/edge/anime/${encodeURIComponent(kitsuId)}/media-relationships?include=destination&page%5Blimit%5D=20`),entries=filterAnimeRelationships(result);mediaDb.putCache(key,entries,24*60*60*1000);return entries}catch(error){logError('catalog:related:anime',error);return mediaDb.getCache(key,{allowExpired:true})||[]}}
function tmdbId(value){const n=Number(value);return Number.isInteger(n)&&n>0?n:null}
async function relatedMovie(imdbId){const{apiKey}=tmdbCredentials();if(!apiKey)return[];const key=`related:v1:movie:${imdbId}`,cached=mediaDb.getCache(key);if(cached)return cached;try{const found=await getJson(`https://api.themoviedb.org/3/find/${encodeURIComponent(imdbId)}?api_key=${encodeURIComponent(apiKey)}&external_source=imdb_id`),tmdbMovieId=tmdbId(found.movie_results?.[0]?.id);if(!tmdbMovieId)return[];const detail=await getJson(`https://api.themoviedb.org/3/movie/${tmdbMovieId}?api_key=${encodeURIComponent(apiKey)}`),collectionId=tmdbId(detail.belongs_to_collection?.id);if(!collectionId)return[];const collection=await getJson(`https://api.themoviedb.org/3/collection/${collectionId}?api_key=${encodeURIComponent(apiKey)}`),parts=(collection.parts||[]).filter(p=>tmdbId(p.id)&&tmdbId(p.id)!==tmdbMovieId);const resolved=(await Promise.all(parts.map(async part=>{try{const partId=tmdbId(part.id);if(!partId)return null;const external=await getJson(`https://api.themoviedb.org/3/movie/${partId}/external_ids?api_key=${encodeURIComponent(apiKey)}`);return external.imdb_id?normalizeTmdbCollectionPart(part,external.imdb_id):null}catch{return null}}))).filter(Boolean);mediaDb.putCache(key,resolved,7*24*60*60*1000);return resolved}catch(error){logError('catalog:related:movie',error);return mediaDb.getCache(key,{allowExpired:true})||[]}}
async function simklWatchedHistory(){if(!simklCredentials().accessToken)return[];const key='simkl:watched:v1';const cached=mediaDb.getCache(key);if(cached)return cached;try{const[movies,shows]=await Promise.all([simklRequest('/sync/all-items/movies/completed?extended=full'),simklRequest('/sync/all-items/shows/all?extended=full&episode_watched_at=yes')]);const entries=watchedFromAllItems(movies,shows);mediaDb.putCache(key,entries,20*60*1000);return entries}catch(error){logError('simkl:watched-history',error);return mediaDb.getCache(key,{allowExpired:true})||[]}}
function updateStatus(win,state,extra={}){if(!win.isDestroyed())win.webContents.send('update:status',{state,...extra})}
function setupAutoUpdater(win){if(!app.isPackaged)return;autoUpdater.autoDownload=true;autoUpdater.autoInstallOnAppQuit=true;autoUpdater.on('checking-for-update',()=>updateStatus(win,'checking'));autoUpdater.on('update-available',info=>{updateReady=false;updateStatus(win,'available',{version:info.version})});autoUpdater.on('update-not-available',()=>updateStatus(win,'current',{version:app.getVersion()}));autoUpdater.on('download-progress',p=>updateStatus(win,'downloading',{percent:Math.round(p.percent)}));autoUpdater.on('update-downloaded',info=>{updateReady=true;updateStatus(win,'ready',{version:info.version})});autoUpdater.on('error',error=>{logError('autoUpdater',error);updateStatus(win,'error',{message:error.message})});const check=()=>autoUpdater.checkForUpdates().catch(error=>logError('update:background-check',error));setTimeout(check,10000);setInterval(check,6*60*60*1000)}
function createWindow(){const win=new BrowserWindow({width:1440,height:900,minWidth:980,minHeight:680,backgroundColor:'#070a12',icon:path.join(__dirname,'assets','app-icon.png'),titleBarStyle:'hidden',titleBarOverlay:{color:'#070a12',symbolColor:'#cdd5e5',height:42},webPreferences:{preload:path.join(__dirname,'preload.cjs'),contextIsolation:true,nodeIntegration:false,sandbox:true}});activeWindow=win;win.webContents.on('before-input-event',(event,input)=>{if(input.key==='F11'&&input.type==='keyDown'){event.preventDefault();win.setFullScreen(!win.isFullScreen())}});win.webContents.setWindowOpenHandler(({url})=>{if(isAllowedExternalUrl(url))shell.openExternal(url);return{action:'deny'}});win.webContents.on('will-navigate',(event,url)=>{if(!url.startsWith('file:'))event.preventDefault()});win.webContents.session.setPermissionRequestHandler((_contents,_permission,callback)=>callback(false));win.webContents.session.webRequest.onBeforeSendHeaders({urls:['*://*.youtube.com/*','*://*.youtube-nocookie.com/*','*://*.ytimg.com/*','*://*.googlevideo.com/*']},(details,callback)=>{details.requestHeaders.Referer='https://www.youtube-nocookie.com/';callback({requestHeaders:details.requestHeaders})});win.loadFile(path.join(__dirname,'index.html'));setupAutoUpdater(win)}
const trustedRendererUrl=pathToFileURL(path.join(__dirname,'index.html')).href;
function handle(channel,listener){ipcMain.handle(channel,async(event,...args)=>{if(!isTrustedIpcSender(event.senderFrame?.url,trustedRendererUrl))throw new Error('Unauthorized IPC sender.');try{return await listener(event,...args)}catch(error){logError(channel,error);throw error}})}
handle('app:bootstrap',async()=>{const configured=Boolean(token());if(!configured)return{configured:false};try{const [user,library]=await Promise.all([torbox('/user/me'),torbox('/torrents/mylist',{limit:100})]);return{configured:true,user:user.data||{},library:library.data||[]}}catch(error){return{configured:false,error:error.message}}});
handle('torbox:connect',async(_e,raw)=>{const value=String(raw||'').trim();if(!validateTorBoxToken(value))return{ok:false,message:'Enter the API token shown in TorBox Settings.'};try{const result=await getJson(`${TORBOX}/user/me`,{headers:{Authorization:`Bearer ${value}`}});const s=readSettings();s.torboxToken=encrypt(value);s.onboardingVersion=2;writeSettings(s);return{ok:true,user:result.data||{},message:'TorBox connected.'}}catch(error){return{ok:false,message:error.message}}});
handle('torbox:disconnect',()=>{const s=readSettings();delete s.torboxToken;writeSettings(s);return{ok:true}});
handle('tmdb:connect',async(_e,raw)=>{const value=String(raw||'').trim();if(!value)return{ok:false,message:'Enter a TMDB API key.'};try{const result=await getJson(`https://api.themoviedb.org/3/authentication?api_key=${encodeURIComponent(value)}`);if(!result.success)return{ok:false,message:'That TMDB API key was rejected.'};const s=readSettings();s.tmdbApiKey=encrypt(value);writeSettings(s);return{ok:true,message:'TMDB connected.'}}catch(error){return{ok:false,message:error.message}}});
handle('tmdb:disconnect',()=>{const s=readSettings();delete s.tmdbApiKey;writeSettings(s);return{ok:true}});
handle('os:connect',async(_e,{apiKey,username,password}={})=>{const key=String(apiKey||'').trim(),user=String(username||'').trim(),pass=String(password||'');if(!key||!user||!pass)return{ok:false,message:'Enter your OpenSubtitles API key, username and password.'};try{const token=await osLoginWith(key,user,pass);const s=readSettings();s.osApiKey=encrypt(key);s.osUsername=encrypt(user);s.osPassword=encrypt(pass);s.osToken=encrypt(token);writeSettings(s);return{ok:true,message:'OpenSubtitles connected.'}}catch(error){return{ok:false,message:error.message}}});
handle('os:disconnect',()=>{const s=readSettings();delete s.osApiKey;delete s.osUsername;delete s.osPassword;delete s.osToken;writeSettings(s);return{ok:true}});
handle('subtitles:search',async(_e,{item,playback}={})=>{const language=readSettings().subtitleLanguage||'en',params=buildSearchParams(item||{},{...playback,language}),query=new URLSearchParams(params).toString(),result=await osRequest(`/subtitles?${query}`);return(result.data||[]).map(normalizeSubtitleResult).filter(x=>x.fileId).slice(0,20)});
handle('subtitles:apply',async(_e,{fileId,compatibility,selection}={})=>{if(!activeMediaUrl)throw new Error('No active media is available for subtitles.');const id=Number(fileId);if(!Number.isInteger(id)||id<=0)throw new Error('Invalid subtitle selection.');const srtText=await osDownloadSubtitleText(id);if(!compatibility)return{ok:true,compatibility:false,vttDataUrl:`data:text/vtt;base64,${Buffer.from(srtToVtt(srtText)).toString('base64')}`};clearActiveSubtitle();const dir=subtitleCacheDir();fs.mkdirSync(dir,{recursive:true});const filePath=path.join(dir,`${crypto.randomBytes(16).toString('hex')}.srt`);fs.writeFileSync(filePath,srtText,{mode:0o600});activeSubtitlePath=filePath;const safe={audio:Number.isInteger(selection?.audio)?selection.audio:-1,startTime:Math.max(0,Math.min(Number(selection?.startTime)||0,86400)),externalSubtitlePath:filePath};const started=await vlcTranscoder.start(vlcInstallPath,activeMediaUrl,safe);await playbackProxy.close();return{ok:true,compatibility:true,tracks:activeMediaTracks,...started}});
handle('settings:get',()=>({...publicSettings(readSettings()),appVersion:app.getVersion(),themes:THEMES,torboxConnected:Boolean(token()),tmdbConnected:Boolean(tmdbCredentials().apiKey),osConnected:osConnected(),vlcInstalled:Boolean(vlcInstallPath)}));
handle('settings:set-theme',(_event,value)=>{const s=readSettings();s.theme=normalizeTheme(value);writeSettings(s);return{theme:s.theme}});
handle('settings:set-subtitle-language',(_event,value)=>{const s=readSettings();s.subtitleLanguage=(String(value||'en').trim().toLowerCase().match(/^[a-z-]{2,10}$/)||['en'])[0];writeSettings(s);return{subtitleLanguage:s.subtitleLanguage}});
handle('account:logout',async()=>{await stopPlayback();writeSettings(logoutSettings(readSettings()));return{ok:true}});
handle('catalog:list',async(_e,payload)=>{const kind=payload?.kind,force=payload?.force===true;if(!isValidCatalogKind(kind))throw new Error('Unsupported catalog.');return catalogData(kind,force)});
handle('catalog:meta',async(_e,{type,id})=>metadata(type,id));
handle('catalog:search',async(_e,{kind,query})=>{if(!isValidCatalogKind(kind))throw new Error('Unsupported catalog.');const q=String(query||'').trim();if(q.length<2)return[];return kind==='anime'?kitsuSearch(q):simklSearch(kind,q)});
handle('catalog:related',async(_e,{type,id})=>{if(type==='anime')return relatedAnime(id);if(type==='movie')return relatedMovie(id);return[]});
handle('tracking:list',async()=>{
  const trackedItems=mediaDb.tracked(),history=[...mediaDb.history(),...await simklWatchedHistory()];
  const details=(await Promise.all(trackedItems.filter(x=>x.type!=='movie').map(x=>metadata(x.type,x.id).catch(()=>null)))).filter(Boolean);
  const newEpisodesById=new Map(mediaDb.trackedUpdates(details).map(u=>[String(u.id),u.newEpisodeCount])),airingById=new Map(details.map(d=>[String(d.id),airingStatus(d)]));
  const tracked=trackedItems.map(item=>({...item,newEpisodeCount:newEpisodesById.get(String(item.id))||0,airing:airingById.get(String(item.id))||''}));
  return{tracked,history};
});
handle('tracking:toggle',(_e,item)=>{const tracked=mediaDb.isTracked(item.id);if(tracked)mediaDb.untrack(item.id);else mediaDb.track(item);return{tracked:!tracked}});
handle('tracking:mark-watched',async(_e,{item,playback})=>{mediaDb.markWatched(item,playback||{});const creds=simklCredentials();let simklResult;if(!creds.accessToken)simklResult={simklSynced:false};else{try{await simklRequest('/sync/history',{method:'POST',body:JSON.stringify(historyPayload(item,playback||{}))});simklResult={simklSynced:true}}catch(error){logError('simkl:sync-history',error);simklResult={simklSynced:false,simklError:error.message}}}return{ok:true,...simklResult,...await pushMalProgress(item)}});
handle('tracking:unmark-watched',async(_e,{item,playback})=>{const p=playback||{};mediaDb.unmarkWatched(item.id,p.season,p.episode);const creds=simklCredentials();let simklResult;if(!creds.accessToken)simklResult={simklSynced:false};else{try{await simklRequest('/sync/history/remove',{method:'POST',body:JSON.stringify(historyPayload(item,p))});simklResult={simklSynced:true}}catch(error){logError('simkl:remove-history',error);simklResult={simklSynced:false,simklError:error.message}}}return{ok:true,...simklResult,...await pushMalProgress(item)}});
handle('tracking:mark-season-watched',async(_e,{item,season,episodes})=>{const list=Array.isArray(episodes)?episodes:[];for(const playback of list)mediaDb.markWatched(item,playback);const creds=simklCredentials();let simklResult;if(!creds.accessToken)simklResult={simklSynced:false};else{try{await simklRequest('/sync/history',{method:'POST',body:JSON.stringify(seasonHistoryPayload(item,season,list.map(p=>p.episode)))});simklResult={simklSynced:true}}catch(error){logError('simkl:sync-season-history',error);simklResult={simklSynced:false,simklError:error.message}}}return{ok:true,...simklResult,...await pushMalProgress(item)}});
handle('home:personalized',async()=>{const [movies,series,anime]=await Promise.all(['movie','series','anime'].map(kind=>catalogData(kind).catch(()=>[])));const all=[...movies,...series,...anime];if(!all.length)throw new Error('All catalog sources are currently unavailable.');const history=[...mediaDb.history(),...await simklWatchedHistory()],tracked=mediaDb.tracked(),watchedIds=new Set(history.map(x=>String(x.id))),trackedIds=new Set(tracked.map(x=>String(x.id))),genres=mediaDb.preferredGenres(4);const recommendations=all.filter(x=>!watchedIds.has(String(x.id))&&!trackedIds.has(String(x.id))&&(genres.length===0||x.genres.some(g=>genres.includes(g)))).slice(0,18);const details=(await Promise.all(tracked.filter(x=>x.type!=='movie').map(x=>metadata(x.type,x.id).catch(()=>null)))).filter(Boolean);return{tracked,updates:mediaDb.trackedUpdates(details),continueWatching:continueWatchingList(details,history).slice(0,18),recommendations:recommendations.length?recommendations:all.slice(0,18),preferredGenres:genres}});
handle('stream:resolve',async(_e,{type,id})=>{
  const auth=token();if(!auth)throw new Error('TorBox is not connected.');
  const key=`stream:v1:${type}:${id}`;
  try{
    const config=meteorP2PConfigPath();
    const meteor=await getJson(`https://meteorfortheweebs.midnightignite.me/${config}/stream/${type}/${encodeURIComponent(id)}.json`);
    const discovered=(meteor.streams||[]).filter(s=>/^[a-f0-9]{40}$/i.test(s.infoHash||''));
    if(!discovered.length)return{streams:[],best:null};
    const hashes=[...new Set(discovered.map(s=>s.infoHash.toLowerCase()))].slice(0,100);
    const cached=await getJson(`${TORBOX}/torrents/checkcached?format=object&list_files=true`,{method:'POST',headers:{Authorization:`Bearer ${auth}`,'Content-Type':'application/json'},body:JSON.stringify({hashes})});
    const available=new Set(Array.isArray(cached.data)?cached.data.map(x=>String(x.hash||x).toLowerCase()):Object.keys(cached.data||{}).map(x=>x.toLowerCase()));
    const streams=rankStreams(discovered.filter(s=>available.has(s.infoHash.toLowerCase())).map(s=>({...s,cached:true,compatible:true})));
    const result={streams,best:streams[0]||null};
    if(result.best)mediaDb.putCache(key,result,60*60*1000);
    return result;
  }catch(error){
    const stale=mediaDb.getCache(key,{allowExpired:true});
    if(stale)return stale;
    throw error;
  }
});
handle('play:stream',async(_e,{stream,mediaId})=>{
  const auth=token();const hash=String(stream?.infoHash||'').toLowerCase();if(!/^[a-f0-9]{40}$/.test(hash))throw new Error('The selected source has no valid torrent hash.');
  const existing=await torbox('/torrents/mylist',{limit:1000});let item=(existing.data||[]).find(x=>String(x.hash||'').toLowerCase()===hash);
  if(!item){const magnet=new URL('magnet:');magnet.searchParams.set('xt',`urn:btih:${hash}`);for(const tracker of sanitizeTrackers(stream.sources))magnet.searchParams.append('tr',tracker);const form=new FormData();form.append('magnet',magnet.toString());form.append('add_only_if_cached','true');const created=await getJson(`${TORBOX}/torrents/createtorrent`,{method:'POST',headers:{Authorization:`Bearer ${auth}`},body:form});const torrentId=created.data?.torrent_id;const fetched=await torbox('/torrents/mylist',{id:torrentId,bypass_cache:true});item=Array.isArray(fetched.data)?fetched.data[0]:fetched.data}
  if(!item)throw new Error('TorBox could not prepare the cached torrent.');
  const parts=String(mediaId||'').split(':');const episode=Number(parts.at(-1)),season=Number(parts.at(-2));const episodic=parts.length>=3&&Number.isFinite(season)&&Number.isFinite(episode);const file=selectVideoFile(item.files||[],episodic?season:undefined,episodic?episode:undefined);if(!file)throw new Error('No matching video file was found in the TorBox torrent.');
  const result=await getJson(`${TORBOX}/torrents/requestdl?token=${encodeURIComponent(auth)}&torrent_id=${encodeURIComponent(item.id)}&file_id=${encodeURIComponent(file.id)}&redirect=false`);const url=typeof result.data==='string'?result.data:result.data?.url||result.data?.download_url;if(!url)throw new Error('TorBox did not return a playable URL.');return preparePlayback(url)
});
handle('playback:compatibility',async(_event,selection={})=>{if(!activeMediaUrl)throw new Error('No active media is available for compatibility mode.');const started=await vlcTranscoder.start(vlcInstallPath,activeMediaUrl,selection);await playbackProxy.close();return{tracks:activeMediaTracks,...started}});
handle('playback:select-tracks',async(_event,selection={})=>{if(!activeMediaUrl)throw new Error('No active media is available for track selection.');const safe={audio:Number.isInteger(selection.audio)?selection.audio:-1,subtitle:Number.isInteger(selection.subtitle)?selection.subtitle:-1,startTime:Math.max(0,Math.min(Number(selection.startTime)||0,86400))};const started=await vlcTranscoder.start(vlcInstallPath,activeMediaUrl,safe);await playbackProxy.close();return{tracks:activeMediaTracks,selection:safe,...started}});
handle('playback:stop',async()=>{await stopPlayback();return{ok:true}});
handle('playback:thumbnail',async(_e,seconds)=>{if(!activeMediaUrl)return null;return captureFrame(ffmpegPath,activeMediaUrl,Number(seconds)||0)});
handle('window:toggle-fullscreen',event=>{const win=BrowserWindow.fromWebContents(event.sender);win.setFullScreen(!win.isFullScreen());return{fullScreen:win.isFullScreen()}});
handle('update:check',async()=>{if(!app.isPackaged)return{state:'development',version:app.getVersion()};const result=await autoUpdater.checkForUpdates(),version=result?.updateInfo?.version||app.getVersion();return{state:version===app.getVersion()?'current':'available',version}});
handle('update:install',()=>{if(app.isPackaged&&updateReady)autoUpdater.quitAndInstall(false,true);return{ok:app.isPackaged&&updateReady}});
handle('clipboard:write',(_event,value)=>{clipboard.writeText(String(value||''));return{ok:true}});
handle('open:external',async(_e,url)=>{if(!isAllowedExternalUrl(url))throw new Error('This external link is not permitted.');await shell.openExternal(url);return{ok:true}});
handle('simkl:status',async()=>{const creds=simklCredentials();if(!creds.accessToken)return{connected:false,clientId:creds.clientId};try{const user=await simklRequest('/users/settings',{method:'POST',body:'{}'});return{connected:true,clientId:creds.clientId,user}}catch(error){return{connected:false,clientId:creds.clientId,error:error.message}}});
handle('simkl:start',async(_e,rawClientId)=>{const clientId=String(rawClientId||'').trim();if(clientId.length<8)throw new Error('Enter the client ID from your Simkl developer app.');const result=await getJson(simklUrl('/oauth/pin',clientId),{headers:{'User-Agent':`r3v07v3r-media-hub/${app.getVersion()}`}});const s=readSettings();s.simklClientId=clientId;writeSettings(s);return result});
handle('simkl:poll',async(_e,userCode)=>{const{clientId}=simklCredentials();if(!clientId)throw new Error('Simkl client ID is missing.');const result=await getJson(simklUrl(`/oauth/pin/${encodeURIComponent(userCode)}`,clientId),{headers:{'User-Agent':`r3v07v3r-media-hub/${app.getVersion()}`}});if(result.access_token){const s=readSettings();s.simklAccessToken=encrypt(result.access_token);writeSettings(s);const user=await simklRequest('/users/settings',{method:'POST',body:'{}'});return{connected:true,user}}return{connected:false,pending:result.result==='KO',message:result.message||'Waiting for authorization.'}});
handle('simkl:disconnect',()=>{const s=readSettings();delete s.simklAccessToken;writeSettings(s);return{ok:true}});
handle('mal:status',async()=>{const creds=malCredentials();if(!creds.accessToken)return{connected:false,clientId:creds.clientId};try{const user=await malRequest('/users/@me?fields=name');return{connected:true,clientId:creds.clientId,user}}catch(error){return{connected:false,clientId:creds.clientId,error:error.message}}});
handle('mal:start',async(_e,{clientId:rawClientId,clientSecret:rawClientSecret}={})=>{const clientId=String(rawClientId||'').trim(),clientSecret=String(rawClientSecret||'').trim();if(clientId.length<8)throw new Error('Enter the client ID from your MyAnimeList API app.');const s=readSettings();s.malClientId=clientId;if(clientSecret)s.malClientSecret=encrypt(clientSecret);else delete s.malClientSecret;writeSettings(s);const state=crypto.randomBytes(16).toString('hex'),codeVerifier=crypto.randomBytes(48).toString('base64url'),authorizeUrl=buildAuthorizeUrl(clientId,state,codeVerifier,MAL_REDIRECT_URI);if(!isAllowedExternalUrl(authorizeUrl))throw new Error('MyAnimeList authorization URL was rejected.');const callback=waitForMalCallback(state);await shell.openExternal(authorizeUrl);const code=await callback;const params={client_id:clientId,grant_type:'authorization_code',code,code_verifier:codeVerifier,redirect_uri:MAL_REDIRECT_URI};if(clientSecret)params.client_secret=clientSecret;const result=await malTokenRequest(params);const settings=readSettings();settings.malAccessToken=encrypt(result.access_token);settings.malRefreshToken=encrypt(result.refresh_token||'');settings.malTokenExpiresAt=Date.now()+(Number(result.expires_in)||3600)*1000;writeSettings(settings);const user=await malRequest('/users/@me?fields=name').catch(()=>({}));return{connected:true,user}});
handle('mal:disconnect',()=>{const s=readSettings();delete s.malAccessToken;delete s.malRefreshToken;delete s.malTokenExpiresAt;delete s.malClientSecret;writeSettings(s);stopMalServer();return{ok:true}});
handle('mal:reconcile-preview',async()=>{const rawEntries=await fetchAllMalAnimeList(),malEntries=rawEntries.map(normalizeMalEntry),withKitsuIds=await Promise.all(malEntries.map(async entry=>({...entry,kitsuId:await resolveKitsuIdForMal(entry.malId)}))),history=[...mediaDb.history(),...await simklWatchedHistory()],localProgress=localWatchedEpisodeCounts(history);return computeReconciliation(withKitsuIds,localProgress)});
handle('mal:reconcile-apply',async(_e,diff)=>{const results={toLocal:[],toMal:[],errors:[]};for(const item of diff?.toLocal||[]){try{const episodeNumbers=Array.from({length:item.toEpisode-item.fromEpisode+1},(_,i)=>item.fromEpisode+i),media={id:item.kitsuId,type:'anime',title:item.title};for(const episode of episodeNumbers)mediaDb.markWatched(media,{season:1,episode});if(simklCredentials().accessToken){try{await simklRequest('/sync/history',{method:'POST',body:JSON.stringify(seasonHistoryPayload(media,1,episodeNumbers))})}catch(error){logError('mal:reconcile:simkl-push',error)}}results.toLocal.push(item.kitsuId)}catch(error){results.errors.push({kitsuId:item.kitsuId,error:error.message})}}for(const item of diff?.toMal||[]){try{await malRequest(`/anime/${item.malId}/my_list_status`,{method:'PATCH',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:new URLSearchParams({num_watched_episodes:String(item.watchedEpisodes)})});results.toMal.push(item.malId)}catch(error){results.errors.push({malId:item.malId,error:error.message})}}return results});
handle('simkl:scrobble-start',async(_e,{item,playback})=>{if(!simklCredentials().accessToken)return{connected:false};await simklRequest('/scrobble/start',{method:'POST',body:JSON.stringify(scrobblePayload(item,playback||{},0))});return{connected:true}});
handle('library:list',async()=>{const [result,catalogs]=await Promise.all([torbox('/torrents/mylist',{limit:100,bypass_cache:false}),Promise.all(['movie','series','anime'].map(kind=>catalogData(kind).catch(()=>[])))]);const raw=Array.isArray(result.data)?result.data:[];return raw.map(item=>enrichTorBoxItem(item,catalogs.flat()))});
handle('library:play',async(_e,item)=>{const auth=token();const files=item.files||item.file_list||[];const file=selectVideoFile(files);if(!file)throw new Error('No matching video file was found in this TorBox item.');const torrentId=item.id||item.torrent_id;if(!torrentId)throw new Error('TorBox item has no torrent ID.');const result=await getJson(`${TORBOX}/torrents/requestdl?token=${encodeURIComponent(auth)}&torrent_id=${encodeURIComponent(torrentId)}&file_id=${encodeURIComponent(file.id||file.file_id)}&redirect=false`);const url=typeof result.data==='string'?result.data:result.data?.url||result.data?.download_url;if(!url)throw new Error('TorBox did not return a playable URL.');return preparePlayback(url)});
app.whenReady().then(()=>{mediaDb=createDatabase(path.join(app.getPath('userData'),'media-hub.sqlite'));createWindow();app.on('activate',()=>{if(BrowserWindow.getAllWindows().length===0)createWindow()})});app.on('before-quit',()=>{playbackProxy.close().catch(()=>{});vlcTranscoder.stop().catch(()=>{});try{mediaDb?.close()}catch{}});app.on('window-all-closed',()=>{if(process.platform!=='darwin')app.quit()});
