const {app,BrowserWindow,ipcMain,safeStorage,shell,clipboard}=require('electron');
const path=require('node:path');const fs=require('node:fs');const {spawn}=require('node:child_process');
const {validateTorBoxToken,meteorP2PConfigPath,normalizeMeta,normalizeKitsuAnime,normalizeSimklCatalog,enrichTorBoxItem,rankStreams,selectVideoFile}=require('./core.cjs');
const {createDatabase}=require('./database.cjs');
const {historyPayload,scrobblePayload}=require('./simkl.cjs');
const TORBOX='https://api.torbox.app/v1/api';
let mediaDb;
const settingsPath=()=>path.join(app.getPath('userData'),'settings.json');
function readSettings(){try{return JSON.parse(fs.readFileSync(settingsPath(),'utf8'))}catch{return{}}}
function writeSettings(v){fs.mkdirSync(path.dirname(settingsPath()),{recursive:true});fs.writeFileSync(settingsPath(),JSON.stringify(v,null,2))}
function encrypt(v){if(!safeStorage.isEncryptionAvailable())throw new Error('Windows secure storage is unavailable.');return safeStorage.encryptString(v).toString('base64')}
function decrypt(v){try{return safeStorage.decryptString(Buffer.from(v,'base64'))}catch{return''}}
function token(){const settings=readSettings();return settings.onboardingVersion===2?decrypt(settings.torboxToken||''):''}
function simklCredentials(){const s=readSettings();return{clientId:s.simklClientId||'',accessToken:decrypt(s.simklAccessToken||'')}}
async function launchPlayback(url){
  if(typeof url!=='string'||!/^https?:\/\//.test(url))throw new Error('Invalid playback URL.');
  const candidates=['C:/Program Files/VideoLAN/VLC/vlc.exe','C:/Program Files (x86)/VideoLAN/VLC/vlc.exe'];
  const vlc=candidates.find(fs.existsSync);
  if(vlc){const child=spawn(vlc,[url,'--meta-title=R3V07V3R Media Hub'],{detached:true,stdio:'ignore'});child.unref();return{ok:true,player:'VLC'}}
  await shell.openExternal(url);return{ok:true,player:'system'}
}
async function getJson(url,options={}){const controller=new AbortController();const timer=setTimeout(()=>controller.abort(),30000);try{const response=await fetch(url,{...options,signal:controller.signal});const body=await response.json().catch(()=>({}));if(!response.ok||body.success===false)throw new Error(body.detail||`Request failed (${response.status})`);return body}finally{clearTimeout(timer)}}
async function torbox(pathname,query={}){const auth=token();if(!auth)throw new Error('TorBox is not connected.');const url=new URL(TORBOX+pathname);Object.entries(query).forEach(([k,v])=>v!==undefined&&url.searchParams.set(k,String(v)));return getJson(url,{headers:{Authorization:`Bearer ${auth}`}})}
const catalogUrls={movie:'https://v3-cinemeta.strem.io/catalog/movie/top.json',series:'https://v3-cinemeta.strem.io/catalog/series/top.json'};
async function kitsuCategories(id){const key=`kitsu:categories:${id}`,cached=mediaDb.getCache(key);if(cached)return cached;const result=await getJson(`https://kitsu.io/api/edge/anime/${encodeURIComponent(id)}/categories?page%5Blimit%5D=20`),genres=(result.data||[]).map(x=>x.attributes?.title).filter(Boolean);mediaDb.putCache(key,genres,7*24*60*60*1000);return genres}
async function enrichKitsu(records){const output=[];for(let i=0;i<records.length;i+=5){const batch=records.slice(i,i+5);output.push(...await Promise.all(batch.map(async record=>({...record,attributes:{...record.attributes,genres:await kitsuCategories(record.id)}}))));if(i+5<records.length)await new Promise(resolve=>setTimeout(resolve,600))}return output}
async function simklCatalog(kind){const section=kind==='series'?'tv':'movies',result=await getJson(`https://data.simkl.in/discover/trending/${section}/week_100.json`);return(result||[]).map(x=>normalizeSimklCatalog(x,kind)).filter(x=>x.id&&!x.id.startsWith('simkl:'))}
async function catalogData(kind,force=false){if(!['movie','series','anime'].includes(kind))throw new Error('Unknown catalog.');const key=`catalog:${kind}`;if(!force){const cached=mediaDb.getCache(key);if(cached)return cached}let items;try{if(kind==='anime'){const result=await getJson('https://kitsu.io/api/edge/trending/anime?limit=20');items=(await enrichKitsu(result.data||[])).map(normalizeKitsuAnime)}else{const result=await getJson(catalogUrls[kind]);items=(result.metas||[]).map(x=>normalizeMeta(x,kind));if(!items.length)throw new Error('The primary catalog returned no titles.')}}catch(primaryError){if(kind!=='anime')try{items=await simklCatalog(kind)}catch{items=null}if(!items?.length){const stale=mediaDb.getCache(key,{allowExpired:true});if(stale?.length)return stale;throw primaryError}}mediaDb.putCache(key,items,6*60*60*1000);return items}
function simklEpisode(record,parentId){return{id:`${parentId}:${record.season||1}:${record.episode||1}`,season:Number(record.season)||1,episode:Number(record.episode)||1,number:Number(record.episode)||1,title:record.title||`Episode ${record.episode||1}`,released:record.date||'',description:record.description||'',thumbnail:record.img?`https://simkl.in/episodes/${record.img}_w.jpg`:''}}
async function metadata(type,id){const cacheKey=`meta:v3:${type}:${id}`,cached=mediaDb.getCache(cacheKey);if(cached)return cached;let item;try{if(type==='anime'){const kitsuId=String(id).replace(/^kitsu:/,'').split(':')[0],[result,genres]=await Promise.all([getJson(`https://kitsu.io/api/edge/anime/${encodeURIComponent(kitsuId)}`),kitsuCategories(kitsuId)]);item=normalizeKitsuAnime({...result.data,attributes:{...result.data?.attributes,genres}})}else{const result=await getJson(`https://v3-cinemeta.strem.io/meta/${type}/${encodeURIComponent(id)}.json`);item=normalizeMeta(result.meta||{},type)}}catch(primaryError){const source=(mediaDb.getCache(`catalog:${type}`,{allowExpired:true})||[]).find(x=>String(x.id)===String(id));if(!source)throw primaryError;item={...source,videos:[]};if(type==='series'&&source.simklId){const episodes=await getJson(`https://api.simkl.com/tv/episodes/${encodeURIComponent(source.simklId)}`);item.videos=(episodes||[]).map(x=>simklEpisode(x,id))}}mediaDb.putCache(cacheKey,item,24*60*60*1000);return item}
function simklUrl(pathname,clientId){const url=new URL(pathname,'https://api.simkl.com');url.searchParams.set('client_id',clientId);url.searchParams.set('app-name','r3v07v3r-media-hub');url.searchParams.set('app-version',app.getVersion());return url.toString()}
async function simklRequest(pathname,options={}){const{clientId,accessToken}=simklCredentials();if(!clientId||!accessToken)throw new Error('Simkl is not connected.');return getJson(simklUrl(pathname,clientId),{...options,headers:{'Content-Type':'application/json',Authorization:`Bearer ${accessToken}`,'User-Agent':`r3v07v3r-media-hub/${app.getVersion()}`,...options.headers}})}
function createWindow(){const win=new BrowserWindow({width:1440,height:900,minWidth:980,minHeight:680,backgroundColor:'#070a12',icon:path.join(__dirname,'assets','app-icon.png'),titleBarStyle:'hidden',titleBarOverlay:{color:'#070a12',symbolColor:'#cdd5e5',height:42},webPreferences:{preload:path.join(__dirname,'preload.cjs'),contextIsolation:true,nodeIntegration:false}});win.webContents.on('before-input-event',(event,input)=>{if(input.key==='F11'&&input.type==='keyDown'){event.preventDefault();win.setFullScreen(!win.isFullScreen())}});win.loadFile(path.join(__dirname,'index.html'))}
ipcMain.handle('app:bootstrap',async()=>{const configured=Boolean(token());if(!configured)return{configured:false};try{const [user,library]=await Promise.all([torbox('/user/me'),torbox('/torrents/mylist',{limit:100})]);return{configured:true,user:user.data||{},library:library.data||[]}}catch(error){return{configured:false,error:error.message}}});
ipcMain.handle('torbox:connect',async(_e,raw)=>{const value=String(raw||'').trim();if(!validateTorBoxToken(value))return{ok:false,message:'Enter the API token shown in TorBox Settings.'};try{const result=await getJson(`${TORBOX}/user/me`,{headers:{Authorization:`Bearer ${value}`}});const s=readSettings();s.torboxToken=encrypt(value);s.onboardingVersion=2;writeSettings(s);return{ok:true,user:result.data||{},message:'TorBox connected.'}}catch(error){return{ok:false,message:error.message}}});
ipcMain.handle('torbox:disconnect',()=>{const s=readSettings();delete s.torboxToken;writeSettings(s);return{ok:true}});
ipcMain.handle('catalog:list',async(_e,kind)=>catalogData(kind));
ipcMain.handle('catalog:meta',async(_e,{type,id})=>metadata(type,id));
ipcMain.handle('tracking:list',()=>({tracked:mediaDb.tracked(),history:mediaDb.history()}));
ipcMain.handle('tracking:toggle',(_e,item)=>{const tracked=mediaDb.isTracked(item.id);if(tracked)mediaDb.untrack(item.id);else mediaDb.track(item);return{tracked:!tracked}});
ipcMain.handle('tracking:mark-watched',async(_e,{item,playback})=>{mediaDb.markWatched(item,playback||{});const creds=simklCredentials();if(creds.accessToken)await simklRequest('/sync/history',{method:'POST',body:JSON.stringify(historyPayload(item,playback||{}))});return{ok:true,simklSynced:Boolean(creds.accessToken)}});
ipcMain.handle('home:personalized',async()=>{const [movies,series,anime]=await Promise.all(['movie','series','anime'].map(kind=>catalogData(kind).catch(()=>[])));const all=[...movies,...series,...anime];if(!all.length)throw new Error('All catalog sources are currently unavailable.');const history=mediaDb.history(),tracked=mediaDb.tracked(),watchedIds=new Set(history.map(x=>String(x.id))),trackedIds=new Set(tracked.map(x=>String(x.id))),genres=mediaDb.preferredGenres(4);const recommendations=all.filter(x=>!watchedIds.has(String(x.id))&&!trackedIds.has(String(x.id))&&(genres.length===0||x.genres.some(g=>genres.includes(g)))).slice(0,18);const details=(await Promise.all(tracked.filter(x=>x.type!=='movie').map(x=>metadata(x.type,x.id).catch(()=>null)))).filter(Boolean);return{tracked,updates:mediaDb.trackedUpdates(details),recommendations:recommendations.length?recommendations:all.slice(0,18),preferredGenres:genres}});
ipcMain.handle('stream:resolve',async(_e,{type,id})=>{
  const auth=token();if(!auth)throw new Error('TorBox is not connected.');
  const config=meteorP2PConfigPath();
  const meteor=await getJson(`https://meteorfortheweebs.midnightignite.me/${config}/stream/${type}/${encodeURIComponent(id)}.json`);
  const discovered=(meteor.streams||[]).filter(s=>/^[a-f0-9]{40}$/i.test(s.infoHash||''));
  if(!discovered.length)return{streams:[],best:null};
  const hashes=[...new Set(discovered.map(s=>s.infoHash.toLowerCase()))].slice(0,100);
  const cached=await getJson(`${TORBOX}/torrents/checkcached?format=object&list_files=true`,{method:'POST',headers:{Authorization:`Bearer ${auth}`,'Content-Type':'application/json'},body:JSON.stringify({hashes})});
  const available=new Set(Array.isArray(cached.data)?cached.data.map(x=>String(x.hash||x).toLowerCase()):Object.keys(cached.data||{}).map(x=>x.toLowerCase()));
  const streams=rankStreams(discovered.filter(s=>available.has(s.infoHash.toLowerCase())).map(s=>({...s,cached:true,compatible:true})));
  return{streams,best:streams[0]||null};
});
ipcMain.handle('play:stream',async(_e,{stream,mediaId})=>{
  const auth=token();const hash=String(stream?.infoHash||'').toLowerCase();if(!/^[a-f0-9]{40}$/.test(hash))throw new Error('The selected source has no valid torrent hash.');
  const existing=await torbox('/torrents/mylist',{limit:1000});let item=(existing.data||[]).find(x=>String(x.hash||'').toLowerCase()===hash);
  if(!item){const magnet=new URL('magnet:');magnet.searchParams.set('xt',`urn:btih:${hash}`);for(const source of stream.sources||[])if(source.startsWith('tracker:'))magnet.searchParams.append('tr',source.slice(8));const form=new FormData();form.append('magnet',magnet.toString());form.append('add_only_if_cached','true');const created=await getJson(`${TORBOX}/torrents/createtorrent`,{method:'POST',headers:{Authorization:`Bearer ${auth}`},body:form});const torrentId=created.data?.torrent_id;const fetched=await torbox('/torrents/mylist',{id:torrentId,bypass_cache:true});item=Array.isArray(fetched.data)?fetched.data[0]:fetched.data}
  if(!item)throw new Error('TorBox could not prepare the cached torrent.');
  const parts=String(mediaId||'').split(':');const episode=Number(parts.at(-1)),season=Number(parts.at(-2));const episodic=parts.length>=3&&Number.isFinite(season)&&Number.isFinite(episode);const file=selectVideoFile(item.files||[],episodic?season:undefined,episodic?episode:undefined);if(!file)throw new Error('No matching video file was found in the TorBox torrent.');
  const result=await getJson(`${TORBOX}/torrents/requestdl?token=${encodeURIComponent(auth)}&torrent_id=${encodeURIComponent(item.id)}&file_id=${encodeURIComponent(file.id)}&redirect=false`);const url=typeof result.data==='string'?result.data:result.data?.url||result.data?.download_url;if(!url)throw new Error('TorBox did not return a playable URL.');return launchPlayback(url)
});
ipcMain.handle('play:url',async(_e,url)=>launchPlayback(url));
ipcMain.handle('window:toggle-fullscreen',event=>{const win=BrowserWindow.fromWebContents(event.sender);win.setFullScreen(!win.isFullScreen());return{fullScreen:win.isFullScreen()}});
ipcMain.handle('clipboard:write',(_event,value)=>{clipboard.writeText(String(value||''));return{ok:true}});
ipcMain.handle('open:external',async(_e,url)=>{if(!/^https:\/\//.test(String(url)))throw new Error('Invalid external URL.');await shell.openExternal(url);return{ok:true}});
ipcMain.handle('simkl:status',async()=>{const creds=simklCredentials();if(!creds.accessToken)return{connected:false,clientId:creds.clientId};try{const user=await simklRequest('/users/settings',{method:'POST',body:'{}'});return{connected:true,clientId:creds.clientId,user}}catch(error){return{connected:false,clientId:creds.clientId,error:error.message}}});
ipcMain.handle('simkl:start',async(_e,rawClientId)=>{const clientId=String(rawClientId||'').trim();if(clientId.length<8)throw new Error('Enter the client ID from your Simkl developer app.');const result=await getJson(simklUrl('/oauth/pin',clientId),{headers:{'User-Agent':`r3v07v3r-media-hub/${app.getVersion()}`}});const s=readSettings();s.simklClientId=clientId;writeSettings(s);return result});
ipcMain.handle('simkl:poll',async(_e,userCode)=>{const{clientId}=simklCredentials();if(!clientId)throw new Error('Simkl client ID is missing.');const result=await getJson(simklUrl(`/oauth/pin/${encodeURIComponent(userCode)}`,clientId),{headers:{'User-Agent':`r3v07v3r-media-hub/${app.getVersion()}`}});if(result.access_token){const s=readSettings();s.simklAccessToken=encrypt(result.access_token);writeSettings(s);const user=await simklRequest('/users/settings',{method:'POST',body:'{}'});return{connected:true,user}}return{connected:false,pending:result.result==='KO',message:result.message||'Waiting for authorization.'}});
ipcMain.handle('simkl:disconnect',()=>{const s=readSettings();delete s.simklAccessToken;writeSettings(s);return{ok:true}});
ipcMain.handle('simkl:scrobble-start',async(_e,{item,playback})=>{if(!simklCredentials().accessToken)return{connected:false};await simklRequest('/scrobble/start',{method:'POST',body:JSON.stringify(scrobblePayload(item,playback||{},0))});return{connected:true}});
ipcMain.handle('library:list',async()=>{const [result,catalogs]=await Promise.all([torbox('/torrents/mylist',{limit:100,bypass_cache:false}),Promise.all(['movie','series','anime'].map(kind=>catalogData(kind).catch(()=>[])))]);const raw=Array.isArray(result.data)?result.data:[];return raw.map(item=>enrichTorBoxItem(item,catalogs.flat()))});
ipcMain.handle('library:play',async(_e,item)=>{const auth=token();const files=item.files||item.file_list||[];const file=selectVideoFile(files);const torrentId=item.id||item.torrent_id;if(!torrentId)throw new Error('TorBox item has no torrent ID.');const result=await getJson(`${TORBOX}/torrents/requestdl?token=${encodeURIComponent(auth)}&torrent_id=${encodeURIComponent(torrentId)}&file_id=${encodeURIComponent(file?.id||file?.file_id||0)}&redirect=false`);const url=typeof result.data==='string'?result.data:result.data?.url||result.data?.download_url;if(!url)throw new Error('TorBox did not return a playable URL.');return launchPlayback(url)});
app.whenReady().then(()=>{mediaDb=createDatabase(path.join(app.getPath('userData'),'media-hub.sqlite'));createWindow();app.on('activate',()=>{if(BrowserWindow.getAllWindows().length===0)createWindow()})});app.on('before-quit',()=>{try{mediaDb?.close()}catch{}});app.on('window-all-closed',()=>{if(process.platform!=='darwin')app.quit()});
