const crypto=require('node:crypto');
function isValidEndpoint(endpoint){if(!endpoint||typeof endpoint.ip!=='string'||!Number.isInteger(endpoint.port))return false;if(endpoint.port<1||endpoint.port>65535)return false;return/^[a-zA-Z0-9.:%-]{1,64}$/.test(endpoint.ip)}
function encodeShareCode({lan,wan,secret,name}){if(!isValidEndpoint(lan)||typeof secret!=='string'||!secret)throw new Error('Invalid party endpoint.');const payload=JSON.stringify({v:1,lan,wan:wan&&isValidEndpoint(wan)?wan:null,secret,name:String(name||'').slice(0,40)});return Buffer.from(payload,'utf8').toString('base64url')}
function decodeShareCode(code){try{const payload=JSON.parse(Buffer.from(String(code||''),'base64url').toString('utf8'));if(payload.v!==1||!isValidEndpoint(payload.lan)||typeof payload.secret!=='string'||!payload.secret)return null;if(payload.wan&&!isValidEndpoint(payload.wan))return null;return payload}catch{return null}}
function deriveKey(secret){return crypto.createHash('sha256').update(String(secret)).digest()}
function encryptMessage(secret,payload){const key=deriveKey(secret),iv=crypto.randomBytes(12),cipher=crypto.createCipheriv('aes-256-gcm',key,iv),ciphertext=Buffer.concat([cipher.update(JSON.stringify(payload),'utf8'),cipher.final()]),authTag=cipher.getAuthTag();return JSON.stringify({iv:iv.toString('base64'),ct:ciphertext.toString('base64'),tag:authTag.toString('base64')})}
function decryptMessage(secret,raw){try{const{iv,ct,tag}=JSON.parse(raw),key=deriveKey(secret),decipher=crypto.createDecipheriv('aes-256-gcm',key,Buffer.from(iv,'base64'));decipher.setAuthTag(Buffer.from(tag,'base64'));const plaintext=Buffer.concat([decipher.update(Buffer.from(ct,'base64')),decipher.final()]);return JSON.parse(plaintext.toString('utf8'))}catch{return null}}
function createMemberId(randomBytes=crypto.randomBytes){return randomBytes(8).toString('hex')}
function applyQueueEvent(queue,event){const list=Array.isArray(queue)?queue:[];if(event?.type==='suggest'){if(!event.item||!event.item.id)return list;if(list.some(x=>String(x.item?.id)===String(event.item.id)))return list;return[...list,{queueId:event.queueId,item:event.item,suggestedBy:event.suggestedBy||''}]}if(event?.type==='remove')return list.filter(x=>x.queueId!==event.queueId);if(event?.type==='queue-sync')return Array.isArray(event.queue)?event.queue:list;return list}
module.exports={isValidEndpoint,encodeShareCode,decodeShareCode,deriveKey,encryptMessage,decryptMessage,createMemberId,applyQueueEvent};
