const http=require('node:http');
const crypto=require('node:crypto');
const dns=require('node:dns').promises;
const {Readable}=require('node:stream');

function isPrivateAddress(value){const address=String(value).replace(/^\[|\]$/g,'').toLowerCase();if(address.includes(':'))return address==='::1'||address==='::'||address.startsWith('fc')||address.startsWith('fd')||/^fe[89ab]/.test(address)||address.startsWith('::ffff:127.')||address.startsWith('::ffff:10.')||address.startsWith('::ffff:192.168.');const parts=address.split('.').map(Number);if(parts.length!==4||parts.some(x=>!Number.isInteger(x)||x<0||x>255))return false;const[a,b]=parts;return a===0||a===10||a===127||a>=224||(a===100&&b>=64&&b<=127)||(a===169&&b===254)||(a===172&&b>=16&&b<=31)||(a===192&&b===168)||(a===198&&(b===18||b===19))}
function isAllowedRemoteMediaUrl(value){try{const url=new URL(String(value)),host=url.hostname.replace(/^\[|\]$/g,'').toLowerCase();return url.protocol==='https:'&&!url.username&&!url.password&&Boolean(host)&&!isPrivateAddress(host)&&host!=='localhost'&&!host.endsWith('.localhost')&&!host.endsWith('.local')&&!host.endsWith('.lan')&&!host.endsWith('.internal')}catch{return false}}
function defaultResolveHost(host){return dns.lookup(host,{all:true}).then(rows=>rows.map(row=>row.address))}
function createPlaybackProxy({fetchImpl=globalThis.fetch,randomBytes=crypto.randomBytes,resolveHost=defaultResolveHost}={}){
 let server=null,origin='',sessions=new Map();
 async function assertPublic(urlValue){if(!isAllowedRemoteMediaUrl(urlValue))throw new Error('Playback requires a valid public HTTPS media URL.');const url=new URL(urlValue),addresses=await resolveHost(url.hostname);if(!addresses.length||addresses.some(isPrivateAddress))throw new Error('Playback source resolved to a private network address.')}
 async function safeFetch(urlValue,options){let current=urlValue;for(let redirects=0;redirects<=5;redirects++){await assertPublic(current);const response=await fetchImpl(current,{...options,redirect:'manual'});if(![301,302,303,307,308].includes(response.status))return response;const location=response.headers.get('location');if(!location)throw new Error('Playback redirect did not include a destination.');current=new URL(location,current).toString()}throw new Error('Playback source redirected too many times.')}
 async function listen(){if(server)return;server=http.createServer(async(req,res)=>{try{const match=/^\/media\/([a-f0-9]{64})$/.exec(new URL(req.url,'http://127.0.0.1').pathname),session=match&&sessions.get(match[1]);if(!session||session.expiresAt<Date.now()||!['GET','HEAD'].includes(req.method)){res.writeHead(404,{'cache-control':'no-store'});return res.end()}
  const headers={};if(req.headers.range)headers.Range=req.headers.range;const controller=new AbortController();res.on('close',()=>controller.abort());const upstream=await safeFetch(session.remoteUrl,{headers,signal:controller.signal});if(!isAllowedRemoteMediaUrl(upstream.url||session.remoteUrl)){res.writeHead(502,{'cache-control':'no-store'});return res.end()}
  const forwarded={};for(const name of ['content-type','content-length','content-range','accept-ranges']){const value=upstream.headers.get(name);if(value)forwarded[name]=value}forwarded['cache-control']='no-store';forwarded['x-content-type-options']='nosniff';res.writeHead(upstream.status,forwarded);if(req.method==='HEAD'||!upstream.body)return res.end();Readable.fromWeb(upstream.body).on('error',()=>res.destroy()).pipe(res)}catch(error){if(!res.headersSent)res.writeHead(error?.name==='AbortError'?499:502,{'cache-control':'no-store'});res.end()}});await new Promise((resolve,reject)=>{server.once('error',reject);server.listen(0,'127.0.0.1',()=>{server.off('error',reject);origin=`http://127.0.0.1:${server.address().port}`;resolve()})})}
 async function register(remoteUrl){if(!isAllowedRemoteMediaUrl(remoteUrl))throw new Error('Playback requires a valid HTTPS media URL.');await listen();sessions.clear();const token=randomBytes(32).toString('hex');sessions.set(token,{remoteUrl,expiresAt:Date.now()+6*60*60*1000});return`${origin}/media/${token}`}
 async function close(){sessions.clear();if(!server)return;const active=server;server=null;origin='';await new Promise(resolve=>active.close(()=>resolve()))}
 return{register,close};
}
module.exports={isPrivateAddress,isAllowedRemoteMediaUrl,createPlaybackProxy};
