const catalog=[
{title:'Dune: Part Two',type:'movie',year:2024,detail:'Sci-Fi · Adventure',symbol:'◐',c1:'#c76440',c2:'#262038',quality:'4K'},
{title:'The Batman',type:'movie',year:2022,detail:'Crime · Mystery',symbol:'▲',c1:'#7e1d24',c2:'#0b0d14',quality:'4K'},
{title:'Shōgun',type:'series',year:2024,detail:'Drama · 10 episodes',symbol:'侍',c1:'#a33724',c2:'#16151c',quality:'4K'},
{title:'Fallout',type:'series',year:2024,detail:'Sci-Fi · 8 episodes',symbol:'☢',c1:'#dda637',c2:'#26354a',quality:'4K'},
{title:'Frieren',type:'anime',year:2023,detail:'Fantasy · 28 episodes',symbol:'✧',c1:'#5e82b4',c2:'#25213c',quality:'1080p'},
{title:'Solo Leveling',type:'anime',year:2024,detail:'Action · 12 episodes',symbol:'⚔',c1:'#5b39ac',c2:'#101a35',quality:'1080p'},
{title:'Furiosa',type:'movie',year:2024,detail:'Action · Adventure',symbol:'☼',c1:'#c97631',c2:'#35221d',quality:'4K'},
{title:'3 Body Problem',type:'series',year:2024,detail:'Sci-Fi · 8 episodes',symbol:'◎',c1:'#386879',c2:'#111926',quality:'4K'},
{title:'Kaiju No. 8',type:'anime',year:2024,detail:'Action · 12 episodes',symbol:'怪',c1:'#3b725a',c2:'#1e2631',quality:'1080p'}];
let section='home';
const $=s=>document.querySelector(s);const $$=s=>[...document.querySelectorAll(s)];
function render(){const q=$('#search').value.toLowerCase().trim();const list=catalog.filter(x=>(section==='home'||x.type===section)&&(!q||`${x.title} ${x.year}`.toLowerCase().includes(q)));$('#catalog').innerHTML=list.map(x=>`<article class="card" data-title="${x.title}"><div class="card-art" data-symbol="${x.symbol}" style="--c1:${x.c1};--c2:${x.c2}"><span class="badge">${x.quality}</span><div><h3>${x.title}</h3><p>${x.year} · ${x.detail}</p></div></div></article>`).join('');$('#resultCount').textContent=`${list.length} titles`;$('#sectionTitle').textContent=q?'Search results':section==='home'?'Trending now':section[0].toUpperCase()+section.slice(1);$$('.card').forEach(c=>c.onclick=()=>showTitle(c.dataset.title));}
function showTitle(title){openModal(`<span class="eyebrow">READY TO RESOLVE</span><h2>${title}</h2><p>Connect your TorBox account to resolve cached sources and select the best compatible release automatically.</p><div class="button-row"><button class="primary" id="playModal">▶ Play best</button><button class="secondary">Browse sources</button></div><div class="status-line" id="playStatus"></div>`);$('#playModal').onclick=async()=>{const s=await window.mediaHub.settingsStatus();$('#playStatus').textContent=s.torboxConfigured?'TorBox is connected. Stream-source integration is the next build milestone.':'TorBox is not connected. Open Settings to add your API token.'}}
function openModal(html){$('#modalBody').innerHTML=html;$('#modal').classList.remove('hidden')}
function settings(){openModal(`<span class="eyebrow">BACKEND CONNECTION</span><h2>Connect TorBox</h2><p>Your token is verified directly with TorBox and encrypted using Windows data protection. It is never sent to a media server.</p><div class="field"><label>TORBOX API TOKEN</label><input id="torboxToken" type="password" placeholder="Paste your TorBox API token"></div><div class="button-row"><button class="primary" id="saveToken">Verify & save</button><button class="secondary" id="testToken">Test saved connection</button></div><div class="status-line" id="settingsStatus"></div>`);$('#saveToken').onclick=async()=>{const b=$('#saveToken');b.disabled=true;b.textContent='Checking…';const r=await window.mediaHub.saveTorBox($('#torboxToken').value);$('#settingsStatus').textContent=r.message;b.disabled=false;b.textContent='Verify & save';refreshStatus();};$('#testToken').onclick=async()=>{$('#settingsStatus').textContent='Testing…';const r=await window.mediaHub.testTorBox();$('#settingsStatus').textContent=r.message;refreshStatus();}}
function party(){const alphabet='ABCDEFGHJKLMNPQRSTUVWXYZ23456789';let raw='';for(let i=0;i<6;i++)raw+=alphabet[Math.floor(Math.random()*alphabet.length)];const code=raw.slice(0,3)+'-'+raw.slice(3);openModal(`<span class="eyebrow">WATCH TOGETHER</span><h2>Start a watch party</h2><p>Share this temporary room code with a friend using the same app. Playback synchronization requires the upcoming encrypted rendezvous service.</p><div class="room-code">${code}</div><div class="field"><label>OR JOIN A FRIEND</label><input id="joinCode" maxlength="7" placeholder="ABC-234"></div><div class="button-row"><button class="primary" id="joinRoom">Join room</button><button class="secondary" id="copyCode">Copy code</button></div><div class="status-line" id="partyStatus"></div>`);$('#copyCode').onclick=()=>{navigator.clipboard.writeText(code);$('#partyStatus').textContent='Code copied.'};$('#joinRoom').onclick=()=>{$('#partyStatus').textContent='Online watch-party synchronization is not enabled in this test build.'}}
async function refreshStatus(){const s=await window.mediaHub.settingsStatus();$('#torboxDot').classList.toggle('on',s.torboxConfigured);$('#torboxState').textContent=s.torboxConfigured?'TorBox configured':'TorBox not connected'}
$$('.nav-item[data-section]').forEach(b=>b.onclick=()=>{section=b.dataset.section;$$('.nav-item').forEach(x=>x.classList.remove('active'));b.classList.add('active');render()});$$('[data-action=settings]').forEach(b=>b.onclick=settings);$$('[data-action=party]').forEach(b=>b.onclick=party);$('#search').oninput=render;$('#closeModal').onclick=()=>$('#modal').classList.add('hidden');$('#modal').onclick=e=>{if(e.target===$('#modal'))$('#modal').classList.add('hidden')};$('#heroPlay').onclick=()=>showTitle('Dune: Part Two');render();refreshStatus();