const net=require('node:net');
const crypto=require('node:crypto');
const fs=require('node:fs');
const path=require('node:path');
const {spawn,execFile,execFileSync}=require('node:child_process');
const {isAllowedRemoteMediaUrl}=require('./playback.cjs');
function isValidCompatibilityToken(value){return/^[a-f0-9]{64}$/.test(String(value))}
function cleanSelection(value,fallback=-1){const number=Number(value);return Number.isInteger(number)&&number>=0&&number<100?number:fallback}
function buildVlcArguments(remoteUrl,port,token,selection={}){if(!isAllowedRemoteMediaUrl(remoteUrl))throw new Error('VLC compatibility requires a valid HTTPS media URL.');if(!Number.isInteger(port)||port<1024||port>65535)throw new Error('Invalid VLC compatibility port.');if(!isValidCompatibilityToken(token))throw new Error('Invalid VLC compatibility stream token.');const args=['-I','dummy','--no-one-instance','--no-video-title-show','--quiet'],audio=cleanSelection(selection.audio),subtitle=cleanSelection(selection.subtitle),startTime=Math.max(0,Number(selection.startTime)||0);if(audio>=0)args.push(`--audio-track=${audio}`);if(subtitle>=0)args.push(`--sub-track=${subtitle}`);if(startTime>0)args.push(`--start-time=${Math.floor(startTime)}`);args.push('--sout',`#transcode{vcodec=VP80,vb=2800,scale=1,acodec=vorb,ab=160,channels=2,samplerate=48000,soverlay}:std{access=http,mux=webm,dst=127.0.0.1:${port}/${token}.webm}`,'--sout-keep',remoteUrl);return args}
function mediaLabel(stream,type,ordinal){const tags=stream.tags||{},name=String(tags.title||'').trim(),language=String(tags.language||'').trim().toUpperCase(),codec=String(stream.codec_name||'unknown').toUpperCase(),parts=[];if(name)parts.push(name);else parts.push(`${type[0].toUpperCase()+type.slice(1)} ${ordinal+1}`);if(type==='video'&&stream.width&&stream.height)parts.push(`${stream.width}×${stream.height}`);if(language&&type!=='video')parts.push(language);if(type==='audio'&&stream.channels)parts.push(`${stream.channels}ch`);parts.push(codec);return parts.join(' • ')}
function parseMediaTracks(payload={}){const result={video:[],audio:[],subtitle:[],probed:true};for(const stream of payload.streams||[]){const type=stream.codec_type;if(!result[type])continue;const ordinal=result[type].length;result[type].push({ordinal,index:Number(stream.index),codec:String(stream.codec_name||'unknown').toLowerCase(),language:String(stream.tags?.language||''),title:String(stream.tags?.title||''),label:mediaLabel(stream,type,ordinal),default:Boolean(stream.disposition?.default)})}return result}
const DIRECT_AUDIO_CODECS=new Set(['aac','mp3','opus','vorbis','flac','pcm_s16le','pcm_s24le']);
function needsAudioCompatibility(tracks){const audio=tracks?.audio||[];if(!audio.length)return false;const selected=audio.find(x=>x.default)||audio[0];return!DIRECT_AUDIO_CODECS.has(String(selected.codec||'').toLowerCase())}
function findInTree(root,name,depth=4){if(!root||depth<0||!fs.existsSync(root))return'';let entries=[];try{entries=fs.readdirSync(root,{withFileTypes:true})}catch{return''}for(const entry of entries){const full=path.join(root,entry.name);if(entry.isFile()&&entry.name.toLowerCase()===name)return full}for(const entry of entries){if(entry.isDirectory()){const found=findInTree(path.join(root,entry.name),name,depth-1);if(found)return found}}return''}
function registryInstallDir(key){try{const output=execFileSync('reg',['query',key,'/v','InstallDir'],{windowsHide:true,encoding:'utf8'});return output.match(/InstallDir\s+REG_SZ\s+(.+)/)?.[1]?.trim()||''}catch{return''}}
function findVlc(){const executable='vlc.exe',direct=['C:/Program Files/VideoLAN/VLC/vlc.exe','C:/Program Files (x86)/VideoLAN/VLC/vlc.exe'];for(const candidate of direct)if(fs.existsSync(candidate))return candidate;for(const key of['HKLM\\SOFTWARE\\VideoLAN\\VLC','HKLM\\SOFTWARE\\WOW6432Node\\VideoLAN\\VLC']){const dir=registryInstallDir(key);if(dir){const candidate=path.join(dir,executable);if(fs.existsSync(candidate))return candidate}}for(const dir of String(process.env.PATH||'').split(path.delimiter)){if(!dir)continue;const candidate=path.join(dir,executable);if(fs.existsSync(candidate))return candidate}return''}
function findFfprobe(){const executable=process.platform==='win32'?'ffprobe.exe':'ffprobe',candidates=[process.env.FFPROBE_PATH,...String(process.env.PATH||'').split(path.delimiter).map(dir=>path.join(dir,executable)),path.join(process.env.LOCALAPPDATA||'','Microsoft','WinGet','Packages')];for(const candidate of candidates){if(!candidate)continue;if(fs.existsSync(candidate)&&fs.statSync(candidate).isFile())return candidate;if(candidate.endsWith('Packages')){const found=findInTree(candidate,executable,5);if(found)return found}}return''}
function probeMedia(ffprobePath,remoteUrl,{execFileImpl=execFile,timeout=15000}={}){if(!ffprobePath||!isAllowedRemoteMediaUrl(remoteUrl))return Promise.resolve({video:[],audio:[],subtitle:[],probed:false});return new Promise(resolve=>{execFileImpl(ffprobePath,['-v','error','-show_entries','stream=index,codec_type,codec_name,width,height,channels:stream_tags=language,title:stream_disposition=default','-of','json',remoteUrl],{windowsHide:true,timeout,maxBuffer:4*1024*1024},(error,stdout)=>{if(error)return resolve({video:[],audio:[],subtitle:[],probed:false});try{resolve(parseMediaTracks(JSON.parse(stdout)))}catch{resolve({video:[],audio:[],subtitle:[],probed:false})}})})}
function freePort(){return new Promise((resolve,reject)=>{const server=net.createServer();server.unref();server.once('error',reject);server.listen(0,'127.0.0.1',()=>{const port=server.address().port;server.close(error=>error?reject(error):resolve(port))})})}
function waitForPort(port,timeout=8000,{signal}={}){const started=Date.now();return new Promise((resolve,reject)=>{const attempt=()=>{if(signal?.aborted)return reject(new Error('VLC compatibility mode was cancelled.'));const socket=net.connect({host:'127.0.0.1',port});socket.once('connect',()=>{socket.destroy();resolve()});socket.once('error',()=>{socket.destroy();if(signal?.aborted)reject(new Error('VLC compatibility mode was cancelled.'));else if(Date.now()-started>=timeout)reject(new Error('VLC compatibility mode did not start in time.'));else setTimeout(attempt,150)})};attempt()})}
function createVlcTranscoder({spawnImpl=spawn,randomBytes=crypto.randomBytes}={}){let child=null;async function stop(){if(child&&!child.killed)child.kill();child=null}async function start(vlcPath,remoteUrl,selection={}){if(!vlcPath)throw new Error('VLC is not installed. Install VLC to use compatibility mode.');await stop();const port=await freePort(),token=randomBytes(32).toString('hex'),args=buildVlcArguments(remoteUrl,port,token,selection);child=spawnImpl(vlcPath,args,{windowsHide:true,stdio:'ignore'});const portAbort=new AbortController();const spawnError=new Promise((_resolve,reject)=>{child.once?.('error',error=>{child=null;portAbort.abort();reject(new Error(`VLC failed to start: ${error.message}`))})});spawnError.catch(()=>{});child.unref?.();const portWait=waitForPort(port,8000,{signal:portAbort.signal});portWait.catch(()=>{});await Promise.race([portWait,spawnError]);return{url:`http://127.0.0.1:${port}/${token}.webm`,engine:'VLC audio/video compatibility',compatibility:true}}return{start,stop}}
module.exports={isValidCompatibilityToken,buildVlcArguments,parseMediaTracks,needsAudioCompatibility,findFfprobe,findVlc,probeMedia,createVlcTranscoder};
