const net=require('node:net');
const crypto=require('node:crypto');
const {spawn}=require('node:child_process');
const {isAllowedRemoteMediaUrl}=require('./playback.cjs');
function isValidCompatibilityToken(value){return/^[a-f0-9]{64}$/.test(String(value))}
function buildVlcArguments(remoteUrl,port,token){if(!isAllowedRemoteMediaUrl(remoteUrl))throw new Error('VLC compatibility requires a valid HTTPS media URL.');if(!Number.isInteger(port)||port<1024||port>65535)throw new Error('Invalid VLC compatibility port.');if(!isValidCompatibilityToken(token))throw new Error('Invalid VLC compatibility stream token.');return['-I','dummy','--no-one-instance','--no-video-title-show','--quiet','--sout',`#transcode{vcodec=VP80,vb=2800,scale=1,acodec=vorb,ab=160,channels=2,samplerate=48000}:std{access=http,mux=webm,dst=127.0.0.1:${port}/${token}.webm}`,'--sout-keep',remoteUrl]}
function freePort(){return new Promise((resolve,reject)=>{const server=net.createServer();server.unref();server.once('error',reject);server.listen(0,'127.0.0.1',()=>{const port=server.address().port;server.close(error=>error?reject(error):resolve(port))})})}
function waitForPort(port,timeout=8000){const started=Date.now();return new Promise((resolve,reject)=>{const attempt=()=>{const socket=net.connect({host:'127.0.0.1',port});socket.once('connect',()=>{socket.destroy();resolve()});socket.once('error',()=>{socket.destroy();if(Date.now()-started>=timeout)reject(new Error('VLC compatibility mode did not start in time.'));else setTimeout(attempt,150)})};attempt()})}
function createVlcTranscoder({spawnImpl=spawn,randomBytes=crypto.randomBytes}={}){let child=null;async function stop(){if(child&&!child.killed)child.kill();child=null}async function start(vlcPath,remoteUrl){if(!vlcPath)throw new Error('VLC is not installed. Install VLC to use compatibility mode.');await stop();const port=await freePort(),token=randomBytes(32).toString('hex'),args=buildVlcArguments(remoteUrl,port,token);child=spawnImpl(vlcPath,args,{windowsHide:true,stdio:'ignore'});child.once?.('error',()=>{child=null});child.unref?.();await waitForPort(port);return{url:`http://127.0.0.1:${port}/${token}.webm`,engine:'VLC WebM compatibility'}}return{start,stop}}
module.exports={isValidCompatibilityToken,buildVlcArguments,createVlcTranscoder};
